"""
testing/harness_generator.py

Generates a testing harness for each migrated CPI iFlow:
  1. Mock payload files (XML/JSON/IDoc) based on adapter type and mapping
  2. A pytest test file that sends payloads to the iFlow endpoint and validates responses
  3. A Postman collection JSON for manual testing

Output:
  output/tests/
    payloads/
      {interface_name}_sample.xml (or .json / .idoc)
    test_{interface_name}.py
    postman_collection.json
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Payload templates per format/adapter
# ---------------------------------------------------------------------------

XML_PAYLOAD_TEMPLATE = '''<?xml version="1.0" encoding="UTF-8"?>
<!-- Mock payload for: {interface_name} -->
<!-- Generated by CPI Migration Workbench -->
<!-- Sender: {sender_system} ({sender_adapter}) -->
<!-- Receiver: {receiver_system} ({receiver_adapter}) -->
<{root_element} xmlns="{namespace}">
  <!-- TODO: Replace with actual field structure from PI/PO mapping -->
  <Header>
    <MessageId>{message_id}</MessageId>
    <Timestamp>{timestamp}</Timestamp>
    <SenderSystem>{sender_system}</SenderSystem>
    <ReceiverSystem>{receiver_system}</ReceiverSystem>
  </Header>
  <Payload>
    <!-- Add interface-specific fields here based on original PI/PO mapping -->
    <Field1>SampleValue1</Field1>
    <Field2>SampleValue2</Field2>
  </Payload>
</{root_element}>'''

JSON_PAYLOAD_TEMPLATE = '''{
  "_comment": "Mock payload for {interface_name}",
  "_generated": "{timestamp}",
  "header": {{
    "messageId": "{message_id}",
    "senderSystem": "{sender_system}",
    "receiverSystem": "{receiver_system}",
    "timestamp": "{timestamp}"
  }},
  "payload": {{
    "field1": "SampleValue1",
    "field2": "SampleValue2"
  }}
}}'''

IDOC_PAYLOAD_TEMPLATE = '''<?xml version="1.0" encoding="UTF-8"?>
<!-- IDoc Mock payload for: {interface_name} -->
<ORDERS05>
  <IDOC BEGIN="1">
    <EDI_DC40 SEGMENT="1">
      <TABNAM>EDI_DC40</TABNAM>
      <MANDT>100</MANDT>
      <DOCNUM>0000000000000001</DOCNUM>
      <DOCREL>755</DOCREL>
      <STATUS>30</STATUS>
      <DIRECT>1</DIRECT>
      <OUTMOD>2</OUTMOD>
      <IDOCTYP>{idoc_type}</IDOCTYP>
      <MESTYP>{message_type}</MESTYP>
      <SNDPOR>SAPECC</SNDPOR>
      <SNDPRT>LS</SNDPRT>
      <SNDPRN>{sender_system}</SNDPRN>
      <RCVPOR>SAPCPI</RCVPOR>
      <RCVPRT>LS</RCVPRT>
      <RCVPRN>{receiver_system}</RCVPRN>
      <CREDAT>{date}</CREDAT>
      <CRETIM>{time}</CRETIM>
    </EDI_DC40>
    <!-- TODO: Add E1 segments based on IDoc type {idoc_type} -->
  </IDOC>
</ORDERS05>'''

PYTEST_TEMPLATE = '''"""
Auto-generated test harness for: {interface_name}
CPI iFlow endpoint testing scaffold.

Usage:
  1. Set environment variables:
     export CPI_BASE_URL="https://your-tenant.hana.ondemand.com"
     export CPI_CLIENT_ID="your-client-id"
     export CPI_CLIENT_SECRET="your-client-secret"
  2. Run: pytest test_{safe_name}.py -v

  Or run against local mock: pytest test_{safe_name}.py -v --mock
"""
import os
import pytest
import requests
from requests.auth import HTTPBasicAuth
from pathlib import Path

# ── Configuration ─────────────────────────────────────────────────────────
BASE_URL      = os.getenv("CPI_BASE_URL", "http://localhost:8080")
CLIENT_ID     = os.getenv("CPI_CLIENT_ID", "")
CLIENT_SECRET = os.getenv("CPI_CLIENT_SECRET", "")
TOKEN_URL     = os.getenv("CPI_TOKEN_URL", "")
IFLOW_ID      = "{iflow_id}"
ENDPOINT_PATH = "/http/{safe_name}"
PAYLOAD_FILE  = Path(__file__).parent / "payloads" / "{payload_filename}"


# ── Auth helper ────────────────────────────────────────────────────────────
def get_token() -> str:
    if not CLIENT_ID or not TOKEN_URL:
        return ""
    resp = requests.post(
        TOKEN_URL,
        data={{"grant_type": "client_credentials"}},
        auth=HTTPBasicAuth(CLIENT_ID, CLIENT_SECRET),
        timeout=15,
    )
    resp.raise_for_status()
    return resp.json()["access_token"]


@pytest.fixture(scope="module")
def session():
    s = requests.Session()
    token = get_token()
    if token:
        s.headers["Authorization"] = f"Bearer {{token}}"
    s.headers["Content-Type"] = "{content_type}"
    return s


# ── Tests ──────────────────────────────────────────────────────────────────

class Test{class_name}:
    """Tests for {interface_name} ({sender_adapter} → {receiver_adapter})."""

    def test_payload_file_exists(self):
        """Verify mock payload file was generated."""
        assert PAYLOAD_FILE.exists(), f"Payload file not found: {{PAYLOAD_FILE}}"

    def test_payload_is_valid_{format_lower}(self):
        """Verify mock payload is well-formed."""
        content = PAYLOAD_FILE.read_text("utf-8")
        assert len(content) > 0, "Payload file is empty"
{format_specific_test}

    def test_iflow_endpoint_reachable(self, session):
        """Verify CPI iFlow endpoint responds (not 404/500)."""
        url = f"{{BASE_URL}}{{ENDPOINT_PATH}}"
        try:
            resp = session.get(url, timeout=10)
            # 401 is acceptable (means endpoint exists, auth needed)
            assert resp.status_code not in (404, 500), \\
                f"Endpoint not reachable: {{resp.status_code}}"
        except requests.exceptions.ConnectionError:
            pytest.skip("CPI tenant not reachable — set CPI_BASE_URL env var")

    def test_send_mock_payload(self, session):
        """Send mock payload to iFlow and verify acceptance."""
        url     = f"{{BASE_URL}}{{ENDPOINT_PATH}}"
        payload = PAYLOAD_FILE.read_bytes()
        try:
            resp = session.post(url, data=payload, timeout=30)
            # Accept 200, 202 (async accepted), 204
            assert resp.status_code in (200, 202, 204), \\
                f"Unexpected response: {{resp.status_code}} — {{resp.text[:200]}}"
        except requests.exceptions.ConnectionError:
            pytest.skip("CPI tenant not reachable — set CPI_BASE_URL env var")

    def test_retry_on_failure(self, session):
        """Verify iFlow returns retryable status on bad payload."""
        url = f"{{BASE_URL}}{{ENDPOINT_PATH}}"
        try:
            resp = session.post(url, data=b"INVALID_PAYLOAD", timeout=10)
            # Should return 4xx (bad request) not 5xx (server crash)
            assert resp.status_code < 500, \\
                f"iFlow crashed on bad payload: {{resp.status_code}}"
        except requests.exceptions.ConnectionError:
            pytest.skip("CPI tenant not reachable")

{adapter_specific_tests}
'''

POSTMAN_TEMPLATE = {
    "info": {
        "name": "CPI Migration Tests",
        "_postman_id": "cpi-migration-workbench",
        "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    "item": []
}


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

@dataclass
class HarnessResult:
    interface_name: str
    payload_path: Path
    test_path: Path
    payload_format: str


class HarnessGenerator:

    def __init__(self, output_dir: str):
        self.output_dir  = Path(output_dir)
        self.tests_dir   = self.output_dir / "tests"
        self.payload_dir = self.tests_dir / "payloads"
        self.tests_dir.mkdir(parents=True, exist_ok=True)
        self.payload_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        assessment,             # MigrationAssessment
        cfg=None,               # InterfaceConfig | None
    ) -> HarnessResult:
        iface     = assessment.interface
        safe_name = iface.name.replace(" ", "_").replace("-", "_")
        now       = datetime.now()

        # ── Payload ─────────────────────────────────────────────────
        payload_format, payload_content, payload_ext = self._build_payload(
            iface, cfg, now
        )
        payload_filename = f"{safe_name}_sample{payload_ext}"
        payload_path     = self.payload_dir / payload_filename
        payload_path.write_text(payload_content, "utf-8")

        # ── Pytest file ──────────────────────────────────────────────
        test_content = self._build_pytest(iface, cfg, safe_name,
                                          payload_filename, payload_format)
        test_path = self.tests_dir / f"test_{safe_name}.py"
        test_path.write_text(test_content, "utf-8")

        logger.info("Generated test harness for %s", iface.name)
        return HarnessResult(
            interface_name=iface.name,
            payload_path=payload_path,
            test_path=test_path,
            payload_format=payload_format,
        )

    def generate_all(self, assessments, configs: dict = None) -> list[HarnessResult]:
        configs = configs or {}
        results = []
        postman = dict(POSTMAN_TEMPLATE)
        postman["item"] = []

        for a in assessments:
            try:
                result = self.generate(a, cfg=configs.get(a.interface.name))
                results.append(result)
                postman["item"].append(
                    self._build_postman_item(a.interface, result.payload_path,
                                             result.payload_format)
                )
            except Exception as exc:
                logger.error("Harness generation failed for %s: %s",
                             a.interface.name, exc)

        # Write Postman collection
        postman_path = self.tests_dir / "postman_collection.json"
        postman_path.write_text(json.dumps(postman, indent=2), "utf-8")
        logger.info("Generated %d test harnesses", len(results))
        return results

    # ── Payload builders ─────────────────────────────────────────────

    def _build_payload(self, iface, cfg, now) -> tuple[str, str, str]:
        adapter = iface.sender_adapter
        ns      = iface.namespace or "http://company.com/integration"
        root    = iface.name.replace(" ", "").replace("-", "")

        if adapter == "IDoc":
            idoc_type = (cfg.message.idoc_type if cfg else "") or "ORDERS05"
            msg_type  = (cfg.message.idoc_message_type if cfg else "") or "ORDERS"
            content   = IDOC_PAYLOAD_TEMPLATE.format(
                interface_name=iface.name,
                idoc_type=idoc_type,
                message_type=msg_type,
                sender_system=iface.sender_system or "SENDER",
                receiver_system=iface.receiver_system or "RECEIVER",
                date=now.strftime("%Y%m%d"),
                time=now.strftime("%H%M%S"),
            )
            return "idoc", content, ".xml"

        msg_format = (cfg.message.format if cfg else "XML") or "XML"

        if msg_format == "JSON":
            content = JSON_PAYLOAD_TEMPLATE.format(
                interface_name=iface.name,
                message_id=f"MSG-{now.strftime('%Y%m%d%H%M%S')}",
                timestamp=now.isoformat(),
                sender_system=iface.sender_system or "SENDER",
                receiver_system=iface.receiver_system or "RECEIVER",
            )
            return "json", content, ".json"

        # Default XML
        content = XML_PAYLOAD_TEMPLATE.format(
            interface_name=iface.name,
            root_element=root or "Message",
            namespace=ns,
            message_id=f"MSG-{now.strftime('%Y%m%d%H%M%S')}",
            timestamp=now.isoformat(),
            sender_system=iface.sender_system or "SENDER",
            receiver_system=iface.receiver_system or "RECEIVER",
            sender_adapter=iface.sender_adapter,
            receiver_adapter=iface.receiver_adapter,
        )
        return "xml", content, ".xml"

    def _build_pytest(self, iface, cfg, safe_name,
                      payload_filename, payload_format) -> str:
        class_name   = "".join(w.capitalize() for w in safe_name.split("_"))
        content_type = "application/xml"
        if payload_format == "json":
            content_type = "application/json"

        format_specific = ""
        if payload_format == "xml":
            format_specific = '''\n        import xml.etree.ElementTree as ET
        ET.fromstring(PAYLOAD_FILE.read_bytes())  # raises if invalid XML'''
        elif payload_format == "json":
            format_specific = '''\n        import json
        json.loads(PAYLOAD_FILE.read_text())  # raises if invalid JSON'''

        adapter_tests = self._adapter_specific_tests(iface, cfg)

        return PYTEST_TEMPLATE.format(
            interface_name=iface.name,
            safe_name=safe_name,
            iflow_id=safe_name,
            payload_filename=payload_filename,
            content_type=content_type,
            class_name=class_name,
            sender_adapter=iface.sender_adapter,
            receiver_adapter=iface.receiver_adapter,
            format_lower=payload_format,
            format_specific_test=format_specific,
            adapter_specific_tests=adapter_tests,
        )

    @staticmethod
    def _adapter_specific_tests(iface, cfg) -> str:
        tests = []
        if iface.sender_adapter == "IDoc":
            tests.append('''
    def test_idoc_structure(self):
        """Verify IDoc payload has required EDI_DC40 control record."""
        content = PAYLOAD_FILE.read_text("utf-8")
        assert "EDI_DC40" in content, "Missing IDoc control record EDI_DC40"
        assert "IDOCTYP" in content, "Missing IDOCTYP field"''')

        if iface.sender_adapter in ("File", "SFTP", "FTP"):
            tests.append('''
    def test_file_payload_encoding(self):
        """Verify file payload is valid UTF-8."""
        content = PAYLOAD_FILE.read_bytes()
        content.decode("utf-8")  # raises if not valid UTF-8''')

        if cfg and cfg.reliability.retry_enabled:
            tests.append(f'''
    def test_retry_configuration(self):
        """Document expected retry behaviour for this interface."""
        # Max retries: {cfg.reliability.retry_max_attempts}
        # Delay: {cfg.reliability.retry_delay_sec}s
        # This test documents the expected retry config — verify in CPI Monitor
        assert True  # Placeholder — verify in CPI Message Monitor after deployment''')

        return "\n".join(tests)

    @staticmethod
    def _build_postman_item(iface, payload_path: Path, fmt: str) -> dict:
        safe = iface.name.replace(" ", "_")
        return {
            "name": iface.name,
            "request": {
                "method": "POST",
                "header": [
                    {"key": "Content-Type",
                     "value": "application/json" if fmt == "json" else "application/xml"},
                    {"key": "Authorization",
                     "value": "Bearer {{cpi_token}}"},
                ],
                "body": {
                    "mode": "raw",
                    "raw": payload_path.read_text("utf-8") if payload_path.exists() else "",
                    "options": {"raw": {"language": fmt}},
                },
                "url": {
                    "raw": f"{{{{cpi_base_url}}}}/http/{safe}",
                    "host": ["{{cpi_base_url}}"],
                    "path": ["http", safe],
                },
            },
            "response": [],
        }
