<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ns.hr-xml.org/2004-08-02"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
	<wsdl:types>
		<xsd:schema targetNamespace="http://ns.hr-xml.org/2004-08-02"
			elementFormDefault="qualified" attributeFormDefault="qualified" id="NewDataSet"
			msdata:schemafragmentcount="2" xmlns="http://ns.hr-xml.org/2004-08-02"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
			<xsd:element name="IdValue" nillable="true"
				msdata:Prefix="ns2">
				<xsd:complexType>
					<xsd:simpleContent msdata:Prefix="ns2"
						msdata:ColumnName="IdValue_Text" msdata:Ordinal="1">
						<xsd:extension base="xsd:string">
							<xsd:attribute name="name" type="xsd:string" form="unqualified" />
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="InternetBrowserForward">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="ForwardUrl" type="xsd:string"
							minOccurs="0" form="unqualified" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="AssessmentOrderRequest" msdata:Prefix="ns2">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="ClientId" minOccurs="0" maxOccurs="unbounded"
							msdata:Prefix="ns2">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element ref="IdValue" minOccurs="0" maxOccurs="unbounded" />
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="PackageId" minOccurs="0" maxOccurs="unbounded"
							msdata:Prefix="ns2">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="IdValue" minOccurs="0" maxOccurs="unbounded" />
		
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="ClientOrderId" minOccurs="0"
							maxOccurs="unbounded" msdata:Prefix="ns2">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="IdValue" type="xsd:string"
										minOccurs="0" msdata:Prefix="ns2" />
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="ComparisonGroupId" minOccurs="0"
							maxOccurs="unbounded" msdata:Prefix="ns2">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="IdValue" type="xsd:string"
										minOccurs="0" msdata:Prefix="ns2" />
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="AssessmentRequester" type="xsd:string"
							minOccurs="0" msdata:Prefix="ns2" />
						<xsd:element name="AssessmentSubject" minOccurs="0"
							maxOccurs="unbounded" msdata:Prefix="ns2">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="SubjectId" minOccurs="0"
										maxOccurs="unbounded" msdata:Prefix="ns2">
										<xsd:complexType>
											<xsd:sequence>
												<xsd:element ref="IdValue" minOccurs="0"
													maxOccurs="unbounded" />
											</xsd:sequence>
										</xsd:complexType>
									</xsd:element>
									<xsd:element name="PersonName" minOccurs="0"
										maxOccurs="unbounded" msdata:Prefix="ns2">
										<xsd:complexType>
											<xsd:sequence>
												<xsd:element name="GivenName" type="xsd:string"
													minOccurs="0" msdata:Prefix="ns2" />
												<xsd:element name="FamilyName" type="xsd:string"
													minOccurs="0" msdata:Prefix="ns2" />
											</xsd:sequence>
										</xsd:complexType>
									</xsd:element>
									<xsd:element name="ContactMethod" minOccurs="0"
										maxOccurs="unbounded" msdata:Prefix="ns2">
										<xsd:complexType>
											<xsd:sequence>
												<xsd:element name="InternetEmailAddress" type="xsd:string"
													minOccurs="0" msdata:Prefix="ns2" />
											</xsd:sequence>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="UserArea" minOccurs="0" maxOccurs="unbounded"
							msdata:Prefix="ns2" form="qualified">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="CompletionSteps" form="unqualified">
										<xsd:complexType>
											<xsd:sequence>
												<xsd:element name="PassCompletionStep"
													minOccurs="0" maxOccurs="unbounded" form="unqualified">
													<xsd:complexType>
														<xsd:sequence>
															<xsd:element ref="InternetBrowserForward"
																minOccurs="0" maxOccurs="unbounded" />
														</xsd:sequence>
													</xsd:complexType>
												</xsd:element>
												<xsd:element name="FailCompletionStep"
													minOccurs="0" maxOccurs="unbounded" form="unqualified">
													<xsd:complexType>
														<xsd:sequence>
															<xsd:element ref="InternetBrowserForward"
																minOccurs="0" maxOccurs="unbounded" />
														</xsd:sequence>
													</xsd:complexType>
												</xsd:element>
											</xsd:sequence>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="AssessmentLanguage" type="xsd:string"
							minOccurs="1" maxOccurs="1" msdata:Prefix="ns2">
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="InternetBrowserForward">
		<wsdl:part name="InternetBrowserForward" element="mstns:InternetBrowserForward"
			xmlns:mstns="http://ns.hr-xml.org/2004-08-02" />
	</wsdl:message>
	<wsdl:message name="NewDataSet">
		<wsdl:part name="NewDataSet" element="mstns:NewDataSet"
			xmlns:mstns="http://ns.hr-xml.org/2004-08-02" />
	</wsdl:message>
	<wsdl:message name="AssessmentOrderRequest">
		<wsdl:part name="AssessmentOrderRequest" element="mstns:AssessmentOrderRequest"
			xmlns:mstns="http://ns.hr-xml.org/2004-08-02" />
	</wsdl:message>
	<wsdl:message name="IdValue">
		<wsdl:part name="IdValue" element="mstns:IdValue"
			xmlns:mstns="http://ns.hr-xml.org/2004-08-02" />
	</wsdl:message>
</wsdl:definitions>
