"""
scaffolder/groovy_generator.py

Converts PI/PO Java mapping patterns to native Apache Groovy scripts
for SAP Cloud Integration.

Handles:
  1. Standard XML transformation (XMLSlurper + XMLBuilder pattern)
  2. Header/property manipulation
  3. Exception handling with MPL logging
  4. Value mapping lookups
  5. Content enricher patterns
  6. Legacy Java wrapper (for complex .jar files)

Output: .groovy files ready to add as Script step in CPI iFlow
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

GROOVY_HEADER = '''import com.sap.gateway.ip.core.customdev.util.Message
import java.util.HashMap
import groovy.xml.XmlSlurper
import groovy.xml.StreamingMarkupBuilder
import groovy.xml.XmlUtil

/**
 * Generated by CPI Migration Scaffolder
 * Original PI/PO mapping: {original_name}
 * Interface: {interface_name}
 * Sender: {sender_system} ({sender_adapter})
 * Receiver: {receiver_system} ({receiver_adapter})
 *
 * TODO: Review and complete field mappings below.
 * All TODO markers indicate sections requiring manual verification.
 */
'''

XML_TRANSFORM_TEMPLATE = '''def Message processData(Message message) {{
    // ── Read input payload ────────────────────────────────────────────
    def body    = message.getBody(String.class)
    def headers = message.getHeaders()
    def props   = message.getProperties()

    try {{
        // ── Parse source XML ──────────────────────────────────────────
        def sourceXml = new XmlSlurper().parseText(body)

        // ── Build target XML ──────────────────────────────────────────
        def targetBuilder = new StreamingMarkupBuilder()
        targetBuilder.encoding = "UTF-8"

        def targetXml = targetBuilder.bind {{
            // TODO: Update namespace and root element to match target schema
            mkp.xmlDeclaration()
            "{target_namespace}".''{target_root}'' {{
{field_mappings}
            }}
        }}

        // ── Set output ────────────────────────────────────────────────
        message.setBody(XmlUtil.serialize(targetXml))

        // ── Set headers for downstream processing ─────────────────────
        message.setHeader("SenderSystem",   "{sender_system}")
        message.setHeader("ReceiverSystem", "{receiver_system}")
        message.setHeader("MessageType",    "{message_type}")

        // ── MPL logging ───────────────────────────────────────────────
        def msgLog = messageLogFactory.getMessageLog(message)
        if (msgLog != null) {{
            msgLog.addCustomHeaderProperty("TransformStatus", "SUCCESS")
            msgLog.addCustomHeaderProperty("SourceNamespace", "{source_namespace}")
        }}

    }} catch (Exception e) {{
        // ── Error handling ────────────────────────────────────────────
        def msgLog = messageLogFactory.getMessageLog(message)
        if (msgLog != null) {{
            msgLog.setStringProperty("ErrorMessage", e.getMessage())
            msgLog.setStringProperty("ErrorClass",   e.getClass().getName())
        }}
        // Re-throw to trigger CPI retry/error handling
        throw new RuntimeException("Transformation failed: ${{e.getMessage()}}", e)
    }}

    return message
}}
'''

HEADER_MANIPULATION_TEMPLATE = '''def Message processData(Message message) {{
    def headers = message.getHeaders()
    def props   = message.getProperties()

    // ── Read source values ────────────────────────────────────────────
    def senderId   = headers.get("SenderID",   "")
    def receiverId = headers.get("ReceiverID",  "")
    def msgId      = headers.get("MessageID",   UUID.randomUUID().toString())

    // ── Set target headers ────────────────────────────────────────────
    // TODO: Map PI/PO header fields to CPI equivalent header names
    message.setHeader("SAP_Sender",           senderId)
    message.setHeader("SAP_Receiver",         receiverId)
    message.setHeader("SAP_MessageProcessingLogID", msgId)

    // ── Set exchange properties ───────────────────────────────────────
    message.setProperty("ProcessingTimestamp", new Date().format("yyyy-MM-dd'T'HH:mm:ss"))

    // ── MPL logging ───────────────────────────────────────────────────
    def msgLog = messageLogFactory.getMessageLog(message)
    if (msgLog != null) {{
        msgLog.addCustomHeaderProperty("HeadersSet", "true")
    }}

    return message
}}
'''

VALUE_MAPPING_TEMPLATE = '''def Message processData(Message message) {{
    def body = message.getBody(String.class)
    def xml  = new XmlSlurper().parseText(body)

    // ── Value mapping table ───────────────────────────────────────────
    // TODO: Replace with actual value mapping from PI/PO value mapping tables
    def valueMappings = [
        // "SOURCE_VALUE": "TARGET_VALUE",
        "ECC":    "S4HANA",
        "01":     "0001",
        // Add more mappings here
    ]

    // ── Apply mappings ────────────────────────────────────────────────
    // Example: map a status code field
    def sourceStatus = xml.Header.Status.text()
    def targetStatus = valueMappings.get(sourceStatus, sourceStatus)

    // ── Rebuild with mapped values ────────────────────────────────────
    // TODO: Update field paths to match your actual schema
    def result = body.replaceAll(
        "<Status>${{sourceStatus}}</Status>",
        "<Status>${{targetStatus}}</Status>"
    )

    message.setBody(result)
    return message
}}
'''

CONTENT_ENRICHER_TEMPLATE = '''def Message processData(Message message) {{
    def body    = message.getBody(String.class)
    def headers = message.getHeaders()

    // ── Extract lookup key from payload ───────────────────────────────
    def xml        = new XmlSlurper().parseText(body)
    def lookupKey  = xml.Payload.KeyField.text()  // TODO: Update field path

    // ── Perform lookup (via HTTP call to external service) ────────────
    // NOTE: In CPI, use a Request-Reply step instead of inline HTTP calls
    // for production. This script handles the response enrichment.
    // The Request-Reply step should call: {enricher_url}

    // ── Process enrichment response ───────────────────────────────────
    def enrichmentData = headers.get("EnrichmentResponse", "")

    if (enrichmentData) {{
        try {{
            def enrichXml = new XmlSlurper().parseText(enrichmentData)
            // TODO: Extract enrichment fields and inject into main payload
            def enrichedField = enrichXml.Result.Value.text()

            // Inject into payload
            def enriched = body.replace(
                "</Payload>",
                "<EnrichedField>${{enrichedField}}</EnrichedField></Payload>"
            )
            message.setBody(enriched)
        }} catch (Exception e) {{
            // Enrichment failed — continue with original payload
            def msgLog = messageLogFactory.getMessageLog(message)
            if (msgLog != null) {{
                msgLog.setStringProperty("EnrichmentWarning", e.getMessage())
            }}
        }}
    }}

    return message
}}
'''

JAVA_WRAPPER_TEMPLATE = '''/**
 * Legacy Java Mapping Wrapper
 * Wraps existing .jar: {jar_name}
 * Class: {java_class}
 *
 * WARNING: This wrapper pattern has known limitations:
 *   - Binary attachments (PDF/Office) will NOT work
 *   - File system I/O will NOT work
 *   - Dynamic property lookups may fail
 * If any of these apply, the mapping must be rewritten natively.
 */
import com.sap.gateway.ip.core.customdev.util.Message

// TODO: Upload {jar_name} to CPI:
//   Monitor → Manage Security Material → (not applicable)
//   OR: Include .jar in iFlow as a Resource file

def Message processData(Message message) {{
    def body = message.getBody(java.io.InputStream.class)

    try {{
        // Instantiate legacy Java class
        // TODO: Verify class is available in iFlow resources
        def mapper = new {java_class}()

        // Prepare inputs (mimics AbstractTransformation interface)
        def inputPayload  = body.bytes
        def outputPayload = new ByteArrayOutputStream()

        // Call legacy mapping method
        // TODO: Replace with actual method signature from original .jar
        mapper.transform(inputPayload, outputPayload)

        message.setBody(new String(outputPayload.toByteArray(), "UTF-8"))

    }} catch (ClassNotFoundException e) {{
        throw new RuntimeException(
            "Legacy Java class {java_class} not found. " +
            "Upload {jar_name} as iFlow resource or rewrite mapping natively.",
            e
        )
    }} catch (Exception e) {{
        throw new RuntimeException("Legacy wrapper failed: ${{e.getMessage()}}", e)
    }}

    return message
}}
'''

EXCEPTION_HANDLER_TEMPLATE = '''def Message processData(Message message) {{
    // ── Standard exception handler ────────────────────────────────────
    // Place this in the Exception Sub-Process of your iFlow

    def exception = message.getProperty("CamelExceptionCaught")
    def headers   = message.getHeaders()

    // Extract error details
    def errorMsg  = exception?.getMessage() ?: "Unknown error"
    def errorType = exception?.getClass()?.getSimpleName() ?: "Exception"
    def msgId     = headers.get("SAP_MessageProcessingLogID", "UNKNOWN")

    // ── MPL logging ───────────────────────────────────────────────────
    def msgLog = messageLogFactory.getMessageLog(message)
    if (msgLog != null) {{
        msgLog.setStringProperty("ErrorType",      errorType)
        msgLog.setStringProperty("ErrorMessage",   errorMsg)
        msgLog.setStringProperty("InterfaceName",  "{interface_name}")
        msgLog.setStringProperty("SenderSystem",   "{sender_system}")
        msgLog.setStringProperty("ReceiverSystem", "{receiver_system}")
        msgLog.addCustomHeaderProperty("ProcessingStatus", "ERROR")
    }}

    // ── Build error payload ───────────────────────────────────────────
    def errorPayload = """<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse>
    <MessageId>${{msgId}}</MessageId>
    <ErrorType>${{errorType}}</ErrorType>
    <ErrorMessage>${{errorMsg}}</ErrorMessage>
    <Interface>{interface_name}</Interface>
    <Timestamp>${{new Date().format("yyyy-MM-dd'T'HH:mm:ss")}}</Timestamp>
</ErrorResponse>"""

    message.setBody(errorPayload)
    message.setHeader("Content-Type", "application/xml")

    // ── Alert (if configured) ─────────────────────────────────────────
    // TODO: Configure alert rules in Monitor → Manage Alerts

    return message
}}
'''


# ---------------------------------------------------------------------------
# Detector
# ---------------------------------------------------------------------------

def detect_mapping_type(mapping_name: str, mapping_content: str = "") -> str:
    """Detect what kind of Groovy script to generate based on mapping name/content."""
    name_lower    = mapping_name.lower()
    content_lower = mapping_content.lower()

    if any(kw in name_lower for kw in ["header", "prop", "property"]):
        return "header"
    if any(kw in name_lower for kw in ["valuemap", "value_map", "lookup", "mapping_table"]):
        return "value_mapping"
    if any(kw in name_lower for kw in ["enrich", "lookup", "content"]):
        return "content_enricher"
    if any(kw in content_lower for kw in [".jar", "class ", "import java"]):
        return "java_wrapper"
    if any(kw in name_lower for kw in ["error", "exception", "fault"]):
        return "exception_handler"
    return "xml_transform"


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

@dataclass
class GroovyScript:
    filename: str
    content: str
    script_type: str
    interface_name: str
    warnings: list[str] = field(default_factory=list)
    local_path: Optional[Path] = None


class GroovyGenerator:

    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir) / "groovy"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        assessment,
        cfg=None,
        mapping_content: str = "",
        jar_class: str = "",
        jar_name: str = "",
    ) -> list[GroovyScript]:
        """Generate all Groovy scripts needed for an interface."""
        iface   = assessment.interface
        scripts = []

        # Main transformation script
        if iface.mapping_program:
            script_type = detect_mapping_type(iface.mapping_program, mapping_content)
            main_script = self._generate_script(
                iface, cfg, script_type,
                jar_class=jar_class, jar_name=jar_name,
            )
            scripts.append(main_script)

        # Always generate exception handler
        error_script = self._generate_exception_handler(iface)
        scripts.append(error_script)

        # Header manipulation if adapters require it
        if iface.sender_adapter in ("IDoc", "RFC") or \
           iface.receiver_adapter in ("IDoc", "RFC"):
            header_script = self._generate_header_script(iface)
            scripts.append(header_script)

        # Write all to disk
        for script in scripts:
            path = self.output_dir / script.filename
            path.write_text(script.content, "utf-8")
            script.local_path = path

        return scripts

    def generate_all(
        self,
        assessments: list,
        configs: dict = None,
    ) -> dict[str, list[GroovyScript]]:
        """Generate scripts for all assessments. Returns {iface_name: [scripts]}."""
        configs = configs or {}
        results = {}
        for a in assessments:
            if not a.interface.mapping_program:
                continue
            try:
                cfg     = configs.get(a.interface.name)
                scripts = self.generate(a, cfg=cfg)
                results[a.interface.name] = scripts
                logger.info("Generated %d Groovy script(s) for %s",
                            len(scripts), a.interface.name)
            except Exception as exc:
                logger.error("Groovy generation failed for %s: %s",
                             a.interface.name, exc)
        return results

    # ── Script builders ───────────────────────────────────────────────

    def _generate_script(
        self,
        iface,
        cfg,
        script_type: str,
        jar_class: str = "",
        jar_name: str = "",
    ) -> GroovyScript:
        safe_name = re.sub(r"[^\w]", "_", iface.name)
        filename  = f"{safe_name}_transform.groovy"
        warnings  = []

        header = GROOVY_HEADER.format(
            original_name=iface.mapping_program or iface.name,
            interface_name=iface.name,
            sender_system=iface.sender_system or "SENDER",
            sender_adapter=iface.sender_adapter,
            receiver_system=iface.receiver_system or "RECEIVER",
            receiver_adapter=iface.receiver_adapter,
        )

        if script_type == "xml_transform":
            ns        = iface.namespace or "http://company.com/integration"
            root      = iface.name.replace(" ", "").replace("-", "") or "Message"
            body      = XML_TRANSFORM_TEMPLATE.format(
                target_namespace=ns,
                target_root=root,
                field_mappings=self._generate_field_mappings(iface, cfg),
                sender_system=iface.sender_system or "SENDER",
                receiver_system=iface.receiver_system or "RECEIVER",
                message_type=iface.message_interface or iface.name,
                source_namespace=ns,
            )

        elif script_type == "header":
            body = HEADER_MANIPULATION_TEMPLATE.format()

        elif script_type == "value_mapping":
            body = VALUE_MAPPING_TEMPLATE.format()

        elif script_type == "content_enricher":
            enricher_url = (cfg.receiver_connectivity.address if cfg else "") or "[ENRICHER_URL]"
            body = CONTENT_ENRICHER_TEMPLATE.format(enricher_url=enricher_url)

        elif script_type == "java_wrapper":
            if not jar_class:
                warnings.append("Java class name not provided — wrapper is incomplete")
            body = JAVA_WRAPPER_TEMPLATE.format(
                jar_name=jar_name or "[mapping.jar]",
                java_class=jar_class or "com.company.mapping.MappingClass",
            )
            warnings += [
                "Binary attachment processing (PDF/Office) will NOT work in wrapper",
                "File system I/O will NOT work — must rewrite natively",
                "Test wrapper thoroughly before production deployment",
            ]

        else:
            body = XML_TRANSFORM_TEMPLATE.format(
                target_namespace=iface.namespace or "http://company.com",
                target_root="Message",
                field_mappings="                // TODO: Add field mappings",
                sender_system=iface.sender_system or "SENDER",
                receiver_system=iface.receiver_system or "RECEIVER",
                message_type=iface.name,
                source_namespace=iface.namespace or "",
            )

        return GroovyScript(
            filename=filename,
            content=header + body,
            script_type=script_type,
            interface_name=iface.name,
            warnings=warnings,
        )

    def _generate_exception_handler(self, iface) -> GroovyScript:
        safe_name = re.sub(r"[^\w]", "_", iface.name)
        content   = GROOVY_HEADER.format(
            original_name="Exception Handler",
            interface_name=iface.name,
            sender_system=iface.sender_system or "SENDER",
            sender_adapter=iface.sender_adapter,
            receiver_system=iface.receiver_system or "RECEIVER",
            receiver_adapter=iface.receiver_adapter,
        ) + EXCEPTION_HANDLER_TEMPLATE.format(
            interface_name=iface.name,
            sender_system=iface.sender_system or "SENDER",
            receiver_system=iface.receiver_system or "RECEIVER",
        )
        return GroovyScript(
            filename=f"{safe_name}_error_handler.groovy",
            content=content,
            script_type="exception_handler",
            interface_name=iface.name,
        )

    def _generate_header_script(self, iface) -> GroovyScript:
        safe_name = re.sub(r"[^\w]", "_", iface.name)
        content   = GROOVY_HEADER.format(
            original_name="Header Manipulation",
            interface_name=iface.name,
            sender_system=iface.sender_system or "SENDER",
            sender_adapter=iface.sender_adapter,
            receiver_system=iface.receiver_system or "RECEIVER",
            receiver_adapter=iface.receiver_adapter,
        ) + HEADER_MANIPULATION_TEMPLATE.format()
        return GroovyScript(
            filename=f"{safe_name}_headers.groovy",
            content=content,
            script_type="header",
            interface_name=iface.name,
        )

    @staticmethod
    def _generate_field_mappings(iface, cfg) -> str:
        """Generate commented field mapping stubs based on known interface info."""
        lines = []
        ns = iface.namespace or "http://company.com"

        if iface.sender_adapter == "IDoc" and cfg:
            lines += [
                f"                // IDoc → XML field mappings",
                f"                // TODO: Map E1 segment fields to target schema",
                f"                'DocumentNumber' sourceXml.IDOC.EDI_DC40.DOCNUM.text()",
                f"                'MessageType'    sourceXml.IDOC.EDI_DC40.MESTYP.text()",
            ]
        elif iface.message_interface:
            lines += [
                f"                // TODO: Map fields from {iface.message_interface}",
                f"                // to target schema",
                f"                'Field1' sourceXml.Payload.Field1.text()",
                f"                'Field2' sourceXml.Payload.Field2.text()",
            ]
        else:
            lines += [
                f"                // TODO: Add field mappings",
                f"                // Pattern: 'TargetField' sourceXml.path.to.field.text()",
            ]

        return "\n".join(lines)
