"""
scaffolder/xslt_generator.py

Generates XSLT 1.0 skeleton stylesheets for interfaces whose source had
an XSLT mapping or whose target system traditionally uses XSLT (B2B
EDIFACT/X12, document compliance, regulatory reporting).

The output is a skeleton, not a full mapping — it gives the consultant
a starting point with namespaces declared, root element matched, and
field-level <xsl:apply-templates> calls stubbed for the common SAP
business-document shapes (IDoc, BAPI, OData). The consultant fills in
the per-field transformations using the field map written as XML
comments above each template.

This generator is intentionally lightweight: PI/PO XSLT mappings are
heavily customised per client, and a generated skeleton with
explanatory comments is more useful than a fake transformation that
would mislead the consultant.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class XSLTScript:
    filename: str
    content: str
    interface_name: str
    target_namespace: str
    warnings: list


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

# The XSLT body uses {} placeholders. To embed a literal { or }, escape with
# {{ or }}. The XML output itself contains XSLT braces (e.g. {fn:current()})
# which need {{ }} to survive .format().

XSLT_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by SAP CPI Migration Scaffolder — XSLT Stylesheet
  ────────────────────────────────────────────────────────────
  Interface         : {interface_name}
  Original mapping  : {original_mapping}
  Sender system     : {sender_system} ({sender_adapter})
  Receiver system   : {receiver_system} ({receiver_adapter})

  USAGE
  ─────
  1. Upload this stylesheet into CPI as an XSLT Mapping artifact.
  2. Reference it from the iFlow's XSLT Mapping step (target step type:
     "XSLT Mapping" in the palette).
  3. Each <xsl:template match="..."> block below is a starting point —
     fill in the source-to-target field logic in your own time.

  COMMON FUNCTIONS YOU MAY NEED
  ─────────────────────────────
  - concat(a, b, c)                          → string concatenation
  - substring(s, start, length)              → string slice (1-indexed!)
  - translate(s, from, to)                   → character-by-character map
  - normalize-space(s)                       → collapse whitespace
  - number(s) / format-number(n, '#.00')     → numeric conversion
  - contains(s, sub) / starts-with(s, sub)   → string search
  - position() / last() / count()            → context functions
  - <xsl:choose>/<xsl:when>/<xsl:otherwise>  → if-then-else
  - <xsl:for-each select="...">              → iterate over nodes
  - <xsl:value-of select="...">              → emit a value
  - <xsl:copy-of select="...">               → copy element + children
-->
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
{extra_namespaces}
  exclude-result-prefixes="xs">

  <xsl:output method="xml" indent="yes" encoding="UTF-8"/>
  <xsl:strip-space elements="*"/>

"""

XSLT_FOOTER = """
</xsl:stylesheet>
"""

# Identity copy template — useful baseline that copies the source verbatim
IDENTITY_TEMPLATE = """  <!-- ─────────────────────────────────────────────────────────────────
       IDENTITY TEMPLATE — copies any unmatched node as-is.
       Remove this if you want strict whitelisting of output elements.
  ───────────────────────────────────────────────────────────────── -->
  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
"""

# Generic root-document template — replace the match attribute with the
# real source root element name once known.
GENERIC_ROOT_TEMPLATE = """  <!-- ─────────────────────────────────────────────────────────────────
       ROOT DOCUMENT TEMPLATE — replace the match="..." attribute with
       the actual source root element name (e.g. match="/Invoice",
       match="/ORDERS05", match="/BusinessPartner").
  ───────────────────────────────────────────────────────────────── -->
  <xsl:template match="/*">
    <{target_root_element}>
      <!-- TODO: Map source fields to target fields here. Examples:
           <TargetField><xsl:value-of select="SourceField"/></TargetField>
           <ConcatField><xsl:value-of select="concat(FieldA, '-', FieldB)"/></ConcatField>
           <ConditionalField>
             <xsl:choose>
               <xsl:when test="Type = 'A'">
                 <xsl:value-of select="ValueA"/>
               </xsl:when>
               <xsl:otherwise>
                 <xsl:value-of select="ValueDefault"/>
               </xsl:otherwise>
             </xsl:choose>
           </ConditionalField>
      -->
    </{target_root_element}>
  </xsl:template>
"""

# IDoc-specific template — provides hints for the SAP IDoc envelope
IDOC_TEMPLATE = """  <!-- ─────────────────────────────────────────────────────────────────
       IDOC ENVELOPE TEMPLATE
       Skeleton for converting an inbound IDoc to your target format.
       SAP IDocs always have an EDI_DC40 control segment + business
       segments. Common control fields to preserve:
         IDOCTYP / MESTYP / SNDPRN / RCVPRN / DOCNUM / CREDAT / CRETIM
  ───────────────────────────────────────────────────────────────── -->
  <xsl:template match="/*">
    <{target_root_element}>
      <Header>
        <DocumentNumber><xsl:value-of select="IDOC/EDI_DC40/DOCNUM"/></DocumentNumber>
        <MessageType><xsl:value-of select="IDOC/EDI_DC40/MESTYP"/></MessageType>
        <SenderPartner><xsl:value-of select="IDOC/EDI_DC40/SNDPRN"/></SenderPartner>
        <ReceiverPartner><xsl:value-of select="IDOC/EDI_DC40/RCVPRN"/></ReceiverPartner>
        <CreatedDate><xsl:value-of select="IDOC/EDI_DC40/CREDAT"/></CreatedDate>
      </Header>
      <Body>
        <!-- TODO: Map your business segments here. Each E1* segment becomes
             a sub-element. Example for the common ORDERS05 IDoc:
             <xsl:for-each select="IDOC/E1EDK01">
               <Order>
                 <PONumber><xsl:value-of select="BELNR"/></PONumber>
                 <Currency><xsl:value-of select="CURCY"/></Currency>
               </Order>
             </xsl:for-each>
        -->
      </Body>
    </{target_root_element}>
  </xsl:template>
"""

# B2B (EDIFACT/X12) template
B2B_TEMPLATE = """  <!-- ─────────────────────────────────────────────────────────────────
       B2B EDI TEMPLATE
       Skeleton for EDIFACT or X12 → target XML. CPI's B2B addon
       converts EDI to its XML representation; this stylesheet
       transforms that XML to your target schema.
  ───────────────────────────────────────────────────────────────── -->
  <xsl:template match="/*">
    <{target_root_element}>
      <!-- EDIFACT envelope: UNB → UNH → message segments → UNT → UNZ
           X12 envelope:     ISA → GS → ST → segments → SE → GE → IEA
           Use xsl:for-each on the repeating segment (e.g. LIN for line items,
           NAD for parties, MOA for amounts) to emit target elements.
      -->
    </{target_root_element}>
  </xsl:template>
"""


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

class XSLTGenerator:
    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir) / "xslt"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def should_generate(self, assessment) -> bool:
        """An interface gets an XSLT stylesheet when any of these hold:

          - mapping_program field references 'xslt' or 'xsl'
          - sender/receiver adapter is AS2, AS4, IDoc (often XSLT in practice)
          - the interface description mentions XSLT/XSL/EDI/EDIFACT/X12

        Other interfaces don't get one — XSLT skeletons for plain HTTPS-to-OData
        flows are pure noise that the consultant would delete.
        """
        iface = assessment.interface
        mapping = (iface.mapping_program or "").lower()
        description = (iface.description or "").lower()
        adapters = (iface.sender_adapter, iface.receiver_adapter)

        if "xslt" in mapping or "xsl" in mapping:
            return True
        if "xslt" in description or "xsl " in description:
            return True
        if "edifact" in description or "edi" in description or "x12" in description:
            return True
        if any(a in ("AS2", "AS4", "IDoc") for a in adapters):
            return True
        return False

    def generate(self, assessment) -> XSLTScript | None:
        """Generate one XSLT skeleton for one assessment. Returns None if
        this interface doesn't warrant a stylesheet."""
        if not self.should_generate(assessment):
            return None

        iface = assessment.interface
        warnings = []

        # Decide which template body to use
        adapters = (iface.sender_adapter, iface.receiver_adapter)
        mapping_lower = (iface.mapping_program or "").lower()
        description_lower = (iface.description or "").lower()

        if "IDoc" in adapters:
            template_body = IDOC_TEMPLATE
            template_kind = "IDoc"
        elif any(a in ("AS2", "AS4") for a in adapters) or \
             any(kw in description_lower for kw in ("edifact", "x12", "edi")):
            template_body = B2B_TEMPLATE
            template_kind = "B2B EDI"
        else:
            template_body = GENERIC_ROOT_TEMPLATE
            template_kind = "Generic"

        # Build target root element name from interface
        target_root = re.sub(r"[^\w]", "", iface.name) or "Document"
        # Capitalise first letter to match XML naming conventions
        target_root = target_root[0].upper() + target_root[1:] if target_root else "Document"

        # Namespaces — declare interface namespace if defined
        extra_ns = ""
        if iface.namespace:
            extra_ns = f'  xmlns:tns="{iface.namespace}"'

        header = XSLT_HEADER.format(
            interface_name=iface.name,
            original_mapping=iface.mapping_program or "(no original mapping name)",
            sender_system=iface.sender_system or "SENDER",
            sender_adapter=iface.sender_adapter,
            receiver_system=iface.receiver_system or "RECEIVER",
            receiver_adapter=iface.receiver_adapter,
            extra_namespaces=extra_ns,
        )
        body = template_body.format(target_root_element=target_root)
        content = header + body + IDENTITY_TEMPLATE + XSLT_FOOTER

        safe_name = re.sub(r"[^\w]", "_", iface.name)[:80]
        return XSLTScript(
            filename=f"{safe_name}.xsl",
            content=content,
            interface_name=iface.name,
            target_namespace=iface.namespace or "",
            warnings=warnings + [f"Template kind: {template_kind} — adjust per client needs"],
        )

    def generate_all(self, assessments: list) -> list[XSLTScript]:
        """Generate XSLT for every applicable assessment. Returns the list
        of generated scripts and writes them to {output_dir}/xslt/."""
        scripts = []
        for a in assessments:
            try:
                script = self.generate(a)
                if script is None:
                    continue
                out_path = self.output_dir / script.filename
                out_path.write_text(script.content, encoding="utf-8")
                scripts.append(script)
            except Exception as exc:
                logger.warning("XSLT generation failed for %s: %s",
                               a.interface.name, exc)
        logger.info("Generated %d XSLT skeleton(s) in %s",
                    len(scripts), self.output_dir)
        return scripts
