<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions targetNamespace="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:n1="urn:sap-com:document:sap:rfc:functions">
 <wsdl:documentation>
  <sidl:sidl xmlns:sidl="http://www.sap.com/2007/03/sidl"/>
 </wsdl:documentation>
 <wsp:UsingPolicy wsdl:required="true"/>
 <wsp:Policy wsu:Id="IF_IF_ISU_C4C_V2_PROMISE_TO_PAY">
  <sapsession:Session xmlns:sapsession="http://www.sap.com/webas/630/soap/features/session/">
   <sapsession:enableSession>false</sapsession:enableSession>
  </sapsession:Session>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2P2pWithdraw">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2P2pReactivate">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2P2pReplace">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2CalcP2pCharges">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2Promise2payGet">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2CalculateP2pRates">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2P2pChangeStatus">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2P2pCreate">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsdl:types>
  <xsd:schema attributeFormDefault="qualified" targetNamespace="urn:sap-com:document:sap:rfc:functions" xmlns:tns="urn:sap-com:document:sap:rfc:functions">
   <xsd:simpleType name="char1">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="1"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char10">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="10"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char100">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="100"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char12">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="12"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char20">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="20"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char220">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="220"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char30">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="30"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char32">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="32"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char4">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="4"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char40">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="40"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char50">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="50"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="cuky5">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="5"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="curr13.2">
    <xsd:restriction base="xsd:decimal">
     <xsd:totalDigits value="13"/>
     <xsd:fractionDigits value="2"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="decimal5.2">
    <xsd:restriction base="xsd:decimal">
     <xsd:totalDigits value="5"/>
     <xsd:fractionDigits value="2"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric3">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="3"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric4">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="4"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric5">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="5"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric6">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="6"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
  </xsd:schema>
  <xsd:schema attributeFormDefault="qualified" targetNamespace="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:n0="urn:sap-com:document:sap:rfc:functions">
   <xsd:import namespace="urn:sap-com:document:sap:rfc:functions"/>
   <xsd:simpleType name="char1">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="1"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char4">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="4"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char50">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="50"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char6">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="6"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:complexType name="IsuC4cV2SAuditLog">
    <xsd:sequence>
     <xsd:element name="UserName" type="n0:char40" minOccurs="0"/>
     <xsd:element name="SystemId" type="n0:char50" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SP2pDetails">
    <xsd:sequence>
     <xsd:element name="PromiseToPayId" type="n0:char12" minOccurs="0"/>
     <xsd:element name="PromisedPartner" type="n0:char10" minOccurs="0"/>
     <xsd:element name="BusinessPartner" type="n0:char10" minOccurs="0"/>
     <xsd:element name="ContractAccount" type="n0:char12" minOccurs="0"/>
     <xsd:element name="Contract" type="n0:char20" minOccurs="0"/>
     <xsd:element name="CompanyCode" type="n0:char4" minOccurs="0"/>
     <xsd:element name="Reason" type="n0:char2" minOccurs="0"/>
     <xsd:element name="WithdrawReason" type="n0:char2" minOccurs="0"/>
     <xsd:element name="Category" type="n0:char2" minOccurs="0"/>
     <xsd:element name="CurrencyKey" type="n0:cuky5" minOccurs="0"/>
     <xsd:element name="PromisedAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="Charges" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="Interest" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="PaymentAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="ClearedAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="CreatedBy" type="n0:char12" minOccurs="0"/>
     <xsd:element name="CreatedOn" type="n0:char10" minOccurs="0"/>
     <xsd:element name="CheckedDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="Status" type="n0:char1" minOccurs="0"/>
     <xsd:element name="LevelFulfillment" type="n0:decimal5.2" minOccurs="0"/>
     <xsd:element name="ReplacementPromisetopay" type="n0:char12" minOccurs="0"/>
     <xsd:element name="PaymentPromisedBytoday" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="AmountPaidBytoday" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="CurrentLevelFulfillment" type="n0:decimal5.2" minOccurs="0"/>
     <xsd:element name="LastPaymentDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="Confirmation" type="n0:char1" minOccurs="0"/>
     <xsd:element name="CustomerName" type="n0:char100" minOccurs="0"/>
     <xsd:element name="NoOfPayments" type="n0:char10" minOccurs="0"/>
     <xsd:element name="PaymentDetails" type="tns:IsuC4cV2TP2pPayments" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cUtilAmount">
    <xsd:sequence>
     <xsd:element name="Amount" type="n0:curr13.2" minOccurs="0"/>
     <xsd:element name="Currency" type="n0:cuky5" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SP2pPayments">
    <xsd:sequence>
     <xsd:element name="PaymentDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="PaymentAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="OpenPaymentAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="PaymentStatusCode" type="n0:char2" minOccurs="0"/>
     <xsd:element name="PaymentStatusText" type="n0:char30" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="Bapiret2">
    <xsd:sequence>
     <xsd:element name="Type" type="n0:char1" minOccurs="0"/>
     <xsd:element name="Id" type="n0:char20" minOccurs="0"/>
     <xsd:element name="Number" type="n0:numeric3" minOccurs="0"/>
     <xsd:element name="Message" type="n0:char220" minOccurs="0"/>
     <xsd:element name="LogNo" type="n0:char20" minOccurs="0"/>
     <xsd:element name="LogMsgNo" type="n0:numeric6" minOccurs="0"/>
     <xsd:element name="MessageV1" type="n0:char50" minOccurs="0"/>
     <xsd:element name="MessageV2" type="n0:char50" minOccurs="0"/>
     <xsd:element name="MessageV3" type="n0:char50" minOccurs="0"/>
     <xsd:element name="MessageV4" type="n0:char50" minOccurs="0"/>
     <xsd:element name="Parameter" type="n0:char32" minOccurs="0"/>
     <xsd:element name="Row" type="xsd:int" minOccurs="0"/>
     <xsd:element name="Field" type="n0:char30" minOccurs="0"/>
     <xsd:element name="System" type="n0:char10" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SAdditionalFields">
    <xsd:sequence>
     <xsd:element name="FirstPaymentDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="PaymentPeriod" type="n0:numeric2" minOccurs="0"/>
     <xsd:element name="NumberOfDates" type="n0:numeric2" minOccurs="0"/>
     <xsd:element name="MaximumPerPayment" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="LevelFulfillmentNew" type="n0:decimal5.2" minOccurs="0"/>
     <xsd:element name="Comments" type="n0:char100" minOccurs="0"/>
     <xsd:element name="WithdrawalInitiator" type="n0:char1" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SOpenItems">
    <xsd:sequence>
     <xsd:element name="BusinessPartnerId" type="n0:char10" minOccurs="0"/>
     <xsd:element name="ContractAccount" type="n0:char12" minOccurs="0"/>
     <xsd:element name="DocumentNumber" type="n0:char12" minOccurs="0"/>
     <xsd:element name="RepetitionItem" type="n0:numeric3" minOccurs="0"/>
     <xsd:element name="ItemNumber" type="n0:numeric4" minOccurs="0"/>
     <xsd:element name="SubItem" type="n0:numeric3" minOccurs="0"/>
     <xsd:element name="MainTransaction" type="n0:char50" minOccurs="0"/>
     <xsd:element name="SubTransaction" type="n0:char50" minOccurs="0"/>
     <xsd:element name="Amount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="ClearedAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="DueDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="DocumentDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="PostingDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="ItemSelected" type="n0:char1" minOccurs="0"/>
     <xsd:element name="ClearingStatus" type="n0:char1" minOccurs="0"/>
     <xsd:element name="LockedStatus" type="tns:char1" minOccurs="0"/>
     <xsd:element name="DunningLevel" type="tns:numeric2" minOccurs="0"/>
     <xsd:element name="DunningText" type="tns:char50" minOccurs="0"/>
     <xsd:element name="DunningStep" type="tns:char4" minOccurs="0"/>
     <xsd:element name="StepName" type="tns:char50" minOccurs="0"/>
     <xsd:element name="ClearingRestriction" type="tns:char1" minOccurs="0"/>
     <xsd:element name="DaysPastDueDate" type="tns:char6" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2TP2pDetails">
    <xsd:sequence>
     <xsd:element name="item" type="tns:IsuC4cV2SP2pDetails" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2TP2pPayments">
    <xsd:sequence>
     <xsd:element name="item" type="tns:IsuC4cV2SP2pPayments" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="Bapirettab">
    <xsd:sequence>
     <xsd:element name="item" type="tns:Bapiret2" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2TOpenItems">
    <xsd:sequence>
     <xsd:element name="item" type="tns:IsuC4cV2SOpenItems" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:element name="IsuC4cV2P2pReactivate">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IsAudit" type="tns:IsuC4cV2SAuditLog" minOccurs="0"/>
      <xsd:element name="ItPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2P2pReactivateResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EtPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
      <xsd:element name="EtReturn" type="tns:Bapirettab" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2P2pWithdraw">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IsAdditionalFields" type="tns:IsuC4cV2SAdditionalFields" minOccurs="0"/>
      <xsd:element name="IsAudit" type="tns:IsuC4cV2SAuditLog" minOccurs="0"/>
      <xsd:element name="ItPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2P2pWithdrawResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EtPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
      <xsd:element name="EtReturn" type="tns:Bapirettab" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2P2pReplace">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IsAdditionalFields" type="tns:IsuC4cV2SAdditionalFields" minOccurs="0"/>
      <xsd:element name="IsAudit" type="tns:IsuC4cV2SAuditLog" minOccurs="0"/>
      <xsd:element name="ItOpenItems" type="tns:IsuC4cV2TOpenItems" minOccurs="0"/>
      <xsd:element name="ItPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2P2pReplaceResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EtPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
      <xsd:element name="EtReturn" type="tns:Bapirettab" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2CalcP2pCharges">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IsAdditionalFields" type="tns:IsuC4cV2SAdditionalFields" minOccurs="0"/>
      <xsd:element name="ItOpenItems" type="tns:IsuC4cV2TOpenItems" minOccurs="0"/>
      <xsd:element name="ItPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2CalcP2pChargesResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EsAdditionalFields" type="tns:IsuC4cV2SAdditionalFields" minOccurs="0"/>
      <xsd:element name="EtPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
      <xsd:element name="EtReturn" type="tns:Bapirettab" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2Promise2payGet">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IvBusinessPartner" type="n0:char10" minOccurs="0"/>
      <xsd:element name="IvContractAccount" type="n0:char12" minOccurs="0"/>
      <xsd:element name="IvMaxCount" type="n0:numeric5" minOccurs="0"/>
      <xsd:element name="IvPromiseToPayId" type="n0:char12" minOccurs="0"/>
      <xsd:element name="IvPromiseToPayStatus" type="n0:char1" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2Promise2payGetResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EtGet" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
      <xsd:element name="EtReturn" type="tns:Bapirettab" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2CalculateP2pRates">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IsAdditionalFields" type="tns:IsuC4cV2SAdditionalFields" minOccurs="0"/>
      <xsd:element name="ItPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2CalculateP2pRatesResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EtPaymentDetails" type="tns:IsuC4cV2TP2pPayments" minOccurs="0"/>
      <xsd:element name="EtReturn" type="tns:Bapirettab" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2P2pChangeStatus">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IsAdditionalFields" type="tns:IsuC4cV2SAdditionalFields" minOccurs="0"/>
      <xsd:element name="IsAudit" type="tns:IsuC4cV2SAuditLog" minOccurs="0"/>
      <xsd:element name="ItPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2P2pChangeStatusResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EtPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
      <xsd:element name="EtReturn" type="tns:Bapirettab" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2P2pCreate">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IsAudit" type="tns:IsuC4cV2SAuditLog" minOccurs="0"/>
      <xsd:element name="ItOpenItems" type="tns:IsuC4cV2TOpenItems" minOccurs="0"/>
      <xsd:element name="ItPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2P2pCreateResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EtPromise2pay" type="tns:IsuC4cV2TP2pDetails" minOccurs="0"/>
      <xsd:element name="EtReturn" type="tns:Bapirettab" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
  </xsd:schema>
 </wsdl:types>
 <wsdl:message name="IsuC4cV2P2pReactivate">
  <wsdl:part name="parameters" element="tns:IsuC4cV2P2pReactivate"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2P2pReactivateResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2P2pReactivateResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2P2pWithdraw">
  <wsdl:part name="parameters" element="tns:IsuC4cV2P2pWithdraw"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2P2pWithdrawResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2P2pWithdrawResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2P2pReplace">
  <wsdl:part name="parameters" element="tns:IsuC4cV2P2pReplace"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2P2pReplaceResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2P2pReplaceResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2CalcP2pCharges">
  <wsdl:part name="parameters" element="tns:IsuC4cV2CalcP2pCharges"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2CalcP2pChargesResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2CalcP2pChargesResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2Promise2payGet">
  <wsdl:part name="parameters" element="tns:IsuC4cV2Promise2payGet"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2Promise2payGetResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2Promise2payGetResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2CalculateP2pRates">
  <wsdl:part name="parameters" element="tns:IsuC4cV2CalculateP2pRates"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2CalculateP2pRatesResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2CalculateP2pRatesResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2P2pChangeStatus">
  <wsdl:part name="parameters" element="tns:IsuC4cV2P2pChangeStatus"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2P2pChangeStatusResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2P2pChangeStatusResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2P2pCreate">
  <wsdl:part name="parameters" element="tns:IsuC4cV2P2pCreate"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2P2pCreateResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2P2pCreateResponse"/>
 </wsdl:message>
 <wsdl:portType name="ISU_C4C_V2_PROMISE_TO_PAY">
  <wsdl:documentation>
   <sapdoc:sapdoc xmlns:sapdoc="urn:sap:esi:documentation">
    <sapdoc:docitem docURL="http://ldciemt.wdf.sap.corp:50022/sap/bc/esdt/docu/sd_text?sap-client=350&amp;sd_name=ISU_C4C_V2_PROMISE_TO_PAY"/>
    <sapdoc:docitem applicationComponent="IS-U-CS-C4C"/>
   </sapdoc:sapdoc>
  </wsdl:documentation>
  <wsp:Policy>
   <wsp:PolicyReference URI="#IF_IF_ISU_C4C_V2_PROMISE_TO_PAY"/>
  </wsp:Policy>
  <wsdl:operation name="IsuC4cV2P2pReactivate">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2P2pReactivate"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2P2pReactivate"/>
   <wsdl:output message="tns:IsuC4cV2P2pReactivateResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2P2pWithdraw">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2P2pWithdraw"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2P2pWithdraw"/>
   <wsdl:output message="tns:IsuC4cV2P2pWithdrawResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2P2pReplace">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2P2pReplace"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2P2pReplace"/>
   <wsdl:output message="tns:IsuC4cV2P2pReplaceResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2CalcP2pCharges">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2CalcP2pCharges"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2CalcP2pCharges"/>
   <wsdl:output message="tns:IsuC4cV2CalcP2pChargesResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2Promise2payGet">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2Promise2payGet"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2Promise2payGet"/>
   <wsdl:output message="tns:IsuC4cV2Promise2payGetResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2CalculateP2pRates">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2CalculateP2pRates"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2CalculateP2pRates"/>
   <wsdl:output message="tns:IsuC4cV2CalculateP2pRatesResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2P2pChangeStatus">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2P2pChangeStatus"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2P2pChangeStatus"/>
   <wsdl:output message="tns:IsuC4cV2P2pChangeStatusResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2P2pCreate">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2P2pCreate"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2P2pCreate"/>
   <wsdl:output message="tns:IsuC4cV2P2pCreateResponse"/>
  </wsdl:operation>
 </wsdl:portType>
</wsdl:definitions>
