<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions targetNamespace="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:n1="urn:sap-com:document:sap:rfc:functions">
 <wsdl:documentation>
  <sidl:sidl xmlns:sidl="http://www.sap.com/2007/03/sidl"/>
 </wsdl:documentation>
 <wsp:UsingPolicy wsdl:required="true"/>
 <wsp:Policy wsu:Id="IF_IF_ISU_C4C_V2_INSTALLMENT_PLAN">
  <sapsession:Session xmlns:sapsession="http://www.sap.com/webas/630/soap/features/session/">
   <sapsession:enableSession>false</sapsession:enableSession>
  </sapsession:Session>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2InstallPlanChange">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2InstallPlanGet">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2InstallPlanCreate">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2InstallmentPlanTy">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2InstallPlanCancel">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsdl:types>
  <xsd:schema attributeFormDefault="qualified" targetNamespace="urn:sap-com:document:sap:rfc:functions" xmlns:tns="urn:sap-com:document:sap:rfc:functions">
   <xsd:simpleType name="char1">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="1"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char10">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="10"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char12">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="12"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char20">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="20"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char220">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="220"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char30">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="30"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char32">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="32"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char4">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="4"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char40">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="40"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char50">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="50"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char6">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="6"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="cuky5">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="5"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="curr13.2">
    <xsd:restriction base="xsd:decimal">
     <xsd:totalDigits value="13"/>
     <xsd:fractionDigits value="2"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric3">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="3"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric4">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="4"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric6">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="6"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
  </xsd:schema>
  <xsd:schema attributeFormDefault="qualified" targetNamespace="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:n0="urn:sap-com:document:sap:rfc:functions">
   <xsd:import namespace="urn:sap-com:document:sap:rfc:functions"/>
   <xsd:complexType name="IsuC4cV2SInstallmentPlan">
    <xsd:sequence>
     <xsd:element name="BusinessPartnerId" type="n0:char10" minOccurs="0"/>
     <xsd:element name="ContractAccountId" type="n0:char12" minOccurs="0"/>
     <xsd:element name="InstallmentPlanNumber" type="n0:char12" minOccurs="0"/>
     <xsd:element name="PlanType" type="n0:char4" minOccurs="0"/>
     <xsd:element name="StartDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="CurrencyCode" type="n0:cuky5" minOccurs="0"/>
     <xsd:element name="InstallmentStatus" type="n0:char2" minOccurs="0"/>
     <xsd:element name="InstallmentAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="NumberOfInstallments" type="n0:numeric3" minOccurs="0"/>
     <xsd:element name="InstallmentInterval" type="n0:numeric2" minOccurs="0"/>
     <xsd:element name="IntervalType" type="n0:char1" minOccurs="0"/>
     <xsd:element name="RemainingAmount" type="n0:char1" minOccurs="0"/>
     <xsd:element name="RoundingAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="TotalAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="ChargeAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="OutstandingAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="Category" type="n0:char2" minOccurs="0"/>
     <xsd:element name="Simulate" type="n0:char1" minOccurs="0"/>
     <xsd:element name="DeactivationReason" type="n0:char2" minOccurs="0"/>
     <xsd:element name="DeactivationDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="EndDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="DeactivationStatus" type="n0:char1" minOccurs="0"/>
     <xsd:element name="InstallmentOpenAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="InstallmentDueAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="InstallmentPaidAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="InstallmentInvoicedAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="OpenItems" type="tns:IsuC4cV2TOpenItems" minOccurs="0"/>
     <xsd:element name="Installments" type="tns:IsuC4cV2TInstallments" minOccurs="0"/>
     <xsd:element name="InstallmentTotalOpenAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cUtilAmount">
    <xsd:sequence>
     <xsd:element name="Amount" type="n0:curr13.2" minOccurs="0"/>
     <xsd:element name="Currency" type="n0:cuky5" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SOpenItems">
    <xsd:sequence>
     <xsd:element name="BusinessPartnerId" type="n0:char10" minOccurs="0"/>
     <xsd:element name="ContractAccount" type="n0:char12" minOccurs="0"/>
     <xsd:element name="DocumentNumber" type="n0:char12" minOccurs="0"/>
     <xsd:element name="SubDocumentNumber" type="n0:char12" minOccurs="0"/>
     <xsd:element name="RepetitionItem" type="n0:numeric3" minOccurs="0"/>
     <xsd:element name="ItemNumber" type="n0:numeric4" minOccurs="0"/>
     <xsd:element name="SubItem" type="n0:numeric3" minOccurs="0"/>
     <xsd:element name="MainTransaction" type="n0:char50" minOccurs="0"/>
     <xsd:element name="SubTransaction" type="n0:char50" minOccurs="0"/>
     <xsd:element name="Amount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="ClearedAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="DueDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="DocumentDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="PostingDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="ItemSelected" type="n0:char1" minOccurs="0"/>
     <xsd:element name="ClearingStatus" type="n0:char1" minOccurs="0"/>
     <xsd:element name="LockedStatus" type="n0:char1" minOccurs="0"/>
     <xsd:element name="DunningLevel" type="n0:numeric2" minOccurs="0"/>
     <xsd:element name="DunningText" type="n0:char50" minOccurs="0"/>
     <xsd:element name="DunningStep" type="n0:char4" minOccurs="0"/>
     <xsd:element name="StepName" type="n0:char50" minOccurs="0"/>
     <xsd:element name="ClearingRestriction" type="n0:char1" minOccurs="0"/>
     <xsd:element name="DaysPastDueDate" type="n0:char6" minOccurs="0"/>
     <xsd:element name="DeferralDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="CanBeReversed" type="n0:char1" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SInstallments">
    <xsd:sequence>
     <xsd:element name="DocumentNumber" type="n0:char12" minOccurs="0"/>
     <xsd:element name="RepetitionItem" type="n0:numeric3" minOccurs="0"/>
     <xsd:element name="ItemNumber" type="n0:numeric4" minOccurs="0"/>
     <xsd:element name="SubItem" type="n0:numeric3" minOccurs="0"/>
     <xsd:element name="DueDate" type="n0:char10" minOccurs="0"/>
     <xsd:element name="InstallmentAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="ClearingStatusCode" type="n0:char1" minOccurs="0"/>
     <xsd:element name="OutstandingAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="PaidAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="ClearingRestriction" type="n0:char1" minOccurs="0"/>
     <xsd:element name="Status" type="n0:char2" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SAuditLog">
    <xsd:sequence>
     <xsd:element name="UserName" type="n0:char40" minOccurs="0"/>
     <xsd:element name="SystemId" type="n0:char50" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="Bapiret2">
    <xsd:sequence>
     <xsd:element name="Type" type="n0:char1" minOccurs="0"/>
     <xsd:element name="Id" type="n0:char20" minOccurs="0"/>
     <xsd:element name="Number" type="n0:numeric3" minOccurs="0"/>
     <xsd:element name="Message" type="n0:char220" minOccurs="0"/>
     <xsd:element name="LogNo" type="n0:char20" minOccurs="0"/>
     <xsd:element name="LogMsgNo" type="n0:numeric6" minOccurs="0"/>
     <xsd:element name="MessageV1" type="n0:char50" minOccurs="0"/>
     <xsd:element name="MessageV2" type="n0:char50" minOccurs="0"/>
     <xsd:element name="MessageV3" type="n0:char50" minOccurs="0"/>
     <xsd:element name="MessageV4" type="n0:char50" minOccurs="0"/>
     <xsd:element name="Parameter" type="n0:char32" minOccurs="0"/>
     <xsd:element name="Row" type="xsd:int" minOccurs="0"/>
     <xsd:element name="Field" type="n0:char30" minOccurs="0"/>
     <xsd:element name="System" type="n0:char10" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SInstallPlanType">
    <xsd:sequence>
     <xsd:element name="InstallmentPlanType" type="n0:char4" minOccurs="0"/>
     <xsd:element name="InstallmentPlanCategory" type="n0:char2" minOccurs="0"/>
     <xsd:element name="CurrencyKey" type="n0:cuky5" minOccurs="0"/>
     <xsd:element name="InstallmentInterval" type="n0:numeric2" minOccurs="0"/>
     <xsd:element name="IntervalType" type="n0:char1" minOccurs="0"/>
     <xsd:element name="NumberOfInstallments" type="n0:numeric3" minOccurs="0"/>
     <xsd:element name="RoundTo" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="DefaultAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="InstallmentAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="ChargeAmount" type="tns:IsuC4cUtilAmount" minOccurs="0"/>
     <xsd:element name="RemainingAmount" type="n0:char1" minOccurs="0"/>
     <xsd:element name="SubTransaction" type="n0:char4" minOccurs="0"/>
     <xsd:element name="Interest" type="n0:char1" minOccurs="0"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2TOpenItems">
    <xsd:sequence>
     <xsd:element name="item" type="tns:IsuC4cV2SOpenItems" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2TInstallments">
    <xsd:sequence>
     <xsd:element name="item" type="tns:IsuC4cV2SInstallments" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="Bapiret2T">
    <xsd:sequence>
     <xsd:element name="item" type="tns:Bapiret2" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2TInstallmentPlan">
    <xsd:sequence>
     <xsd:element name="item" type="tns:IsuC4cV2SInstallmentPlan" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:element name="IsuC4cV2InstallPlanChange">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IsAudit" type="tns:IsuC4cV2SAuditLog" minOccurs="0"/>
      <xsd:element name="IsInstallPlanChange" type="tns:IsuC4cV2SInstallmentPlan" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2InstallPlanChangeResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EsInstallPlanChange" type="tns:IsuC4cV2SInstallmentPlan" minOccurs="0"/>
      <xsd:element name="EtMessages" type="tns:Bapiret2T" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2InstallPlanGet">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IvBusinessPartnerId" type="n0:char10" minOccurs="0"/>
      <xsd:element name="IvContractAccountId" type="n0:char12" minOccurs="0"/>
      <xsd:element name="IvInstallmentPlanNumber" type="n0:char12" minOccurs="0"/>
      <xsd:element name="IvMaxcount" type="xsd:int" minOccurs="0"/>
      <xsd:element name="IvStatus" type="n0:char2" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2InstallPlanGetResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EtInstallPlanGet" type="tns:IsuC4cV2TInstallmentPlan" minOccurs="0"/>
      <xsd:element name="EtMessages" type="tns:Bapiret2T" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2InstallPlanCreate">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IsAudit" type="tns:IsuC4cV2SAuditLog" minOccurs="0"/>
      <xsd:element name="IsInstallPlanCreate" type="tns:IsuC4cV2SInstallmentPlan" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2InstallPlanCreateResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EsInstallPlanCreate" type="tns:IsuC4cV2SInstallmentPlan" minOccurs="0"/>
      <xsd:element name="EtMessages" type="tns:Bapiret2T" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2InstallmentPlanTy">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IvInstallmentPlanType" type="n0:char4" minOccurs="0"/>
      <xsd:element name="IvWaers" type="n0:cuky5" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2InstallmentPlanTyResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EsInstallmentPlanType" type="tns:IsuC4cV2SInstallPlanType" minOccurs="0"/>
      <xsd:element name="EtMessage" type="tns:Bapiret2T" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2InstallPlanCancel">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="IsAudit" type="tns:IsuC4cV2SAuditLog" minOccurs="0"/>
      <xsd:element name="IsInstallPlanCancel" type="tns:IsuC4cV2SInstallmentPlan" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2InstallPlanCancelResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="EsInstallPlanCancel" type="tns:IsuC4cV2SInstallmentPlan" minOccurs="0"/>
      <xsd:element name="EtMessages" type="tns:Bapiret2T" minOccurs="0"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
  </xsd:schema>
 </wsdl:types>
 <wsdl:message name="IsuC4cV2InstallPlanChange">
  <wsdl:part name="parameters" element="tns:IsuC4cV2InstallPlanChange"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2InstallPlanChangeResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2InstallPlanChangeResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2InstallPlanGet">
  <wsdl:part name="parameters" element="tns:IsuC4cV2InstallPlanGet"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2InstallPlanGetResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2InstallPlanGetResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2InstallPlanCreate">
  <wsdl:part name="parameters" element="tns:IsuC4cV2InstallPlanCreate"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2InstallPlanCreateResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2InstallPlanCreateResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2InstallmentPlanTy">
  <wsdl:part name="parameters" element="tns:IsuC4cV2InstallmentPlanTy"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2InstallmentPlanTyResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2InstallmentPlanTyResponse"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2InstallPlanCancel">
  <wsdl:part name="parameters" element="tns:IsuC4cV2InstallPlanCancel"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2InstallPlanCancelResponse">
  <wsdl:part name="parameter" element="tns:IsuC4cV2InstallPlanCancelResponse"/>
 </wsdl:message>
 <wsdl:portType name="ISU_C4C_V2_INSTALLMENT_PLAN">
  <wsdl:documentation>
   <sapdoc:sapdoc xmlns:sapdoc="urn:sap:esi:documentation">
    <sapdoc:docitem docURL="http://ldciemo.wdf.sap.corp:50000/sap/bc/esdt/docu/sd_text?sap-client=300&amp;sd_name=ISU_C4C_V2_INSTALLMENT_PLAN"/>
    <sapdoc:docitem applicationComponent="IS-U-CS-C4C"/>
   </sapdoc:sapdoc>
  </wsdl:documentation>
  <wsp:Policy>
   <wsp:PolicyReference URI="#IF_IF_ISU_C4C_V2_INSTALLMENT_PLAN"/>
  </wsp:Policy>
  <wsdl:operation name="IsuC4cV2InstallPlanChange">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2InstallPlanChange"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2InstallPlanChange"/>
   <wsdl:output message="tns:IsuC4cV2InstallPlanChangeResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2InstallPlanGet">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2InstallPlanGet"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2InstallPlanGet"/>
   <wsdl:output message="tns:IsuC4cV2InstallPlanGetResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2InstallPlanCreate">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2InstallPlanCreate"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2InstallPlanCreate"/>
   <wsdl:output message="tns:IsuC4cV2InstallPlanCreateResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2InstallmentPlanTy">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2InstallmentPlanTy"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2InstallmentPlanTy"/>
   <wsdl:output message="tns:IsuC4cV2InstallmentPlanTyResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2InstallPlanCancel">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2InstallPlanCancel"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2InstallPlanCancel"/>
   <wsdl:output message="tns:IsuC4cV2InstallPlanCancelResponse"/>
  </wsdl:operation>
 </wsdl:portType>
</wsdl:definitions>
