<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:sap-com:document:sap:soap:functions:mc-style">
 <wsdl:documentation>
  <sidl:sidl xmlns:sidl="http://www.sap.com/2007/03/sidl"/>
 </wsdl:documentation>
 <wsp:UsingPolicy wsdl:required="true"/>
 <wsp:Policy wsu:Id="IF_IF_ISU_C4C_V2_PAYMENT_PLAN">
  <sapsession:Session xmlns:sapsession="http://www.sap.com/webas/630/soap/features/session/">
   <sapsession:enableSession>false</sapsession:enableSession>
  </sapsession:Session>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2PaymentPlanCreate">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2PaymentPlanEdit">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2PaymentPlanDelete">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2PplanSimulation">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2PplanDeactivate">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2PaymentPlanGet">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsdl:types>
  <xsd:schema xmlns:tns="urn:sap-com:document:sap:rfc:functions" attributeFormDefault="qualified" targetNamespace="urn:sap-com:document:sap:rfc:functions">
   <xsd:simpleType name="char1">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="1"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char10">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="10"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char12">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="12"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char132">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="132"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char20">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="20"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char220">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="220"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char30">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="30"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char32">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="32"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char4">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="4"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char40">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="40"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char50">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="50"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="cuky5">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="5"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="curr13.2">
    <xsd:restriction base="xsd:decimal">
     <xsd:totalDigits value="13"/>
     <xsd:fractionDigits value="2"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric1">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="1"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric3">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="3"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric4">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="4"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric6">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="6"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
  </xsd:schema>
  <xsd:schema xmlns:n0="urn:sap-com:document:sap:rfc:functions" attributeFormDefault="qualified" targetNamespace="urn:sap-com:document:sap:soap:functions:mc-style">
   <xsd:import namespace="urn:sap-com:document:sap:rfc:functions"/>
   <xsd:simpleType name="char4">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="4"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:complexType name="IsuC4cV2SAuditLog">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="UserName" type="n0:char40"/>
     <xsd:element minOccurs="0" name="SystemId" type="n0:char50"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SPplanDelete">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="PaymentPlanId" type="n0:char12"/>
     <xsd:element minOccurs="0" name="UpdateEverTable" type="n0:char1"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="Bapiret2">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="Type" type="n0:char1"/>
     <xsd:element minOccurs="0" name="Id" type="n0:char20"/>
     <xsd:element minOccurs="0" name="Number" type="n0:numeric3"/>
     <xsd:element minOccurs="0" name="Message" type="n0:char220"/>
     <xsd:element minOccurs="0" name="LogNo" type="n0:char20"/>
     <xsd:element minOccurs="0" name="LogMsgNo" type="n0:numeric6"/>
     <xsd:element minOccurs="0" name="MessageV1" type="n0:char50"/>
     <xsd:element minOccurs="0" name="MessageV2" type="n0:char50"/>
     <xsd:element minOccurs="0" name="MessageV3" type="n0:char50"/>
     <xsd:element minOccurs="0" name="MessageV4" type="n0:char50"/>
     <xsd:element minOccurs="0" name="Parameter" type="n0:char32"/>
     <xsd:element minOccurs="0" name="Row" type="xsd:int"/>
     <xsd:element minOccurs="0" name="Field" type="n0:char30"/>
     <xsd:element minOccurs="0" name="System" type="n0:char10"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SPplanItems">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="DocumentNumber" type="n0:char12"/>
     <xsd:element minOccurs="0" name="RepetitionItem" type="n0:numeric3"/>
     <xsd:element minOccurs="0" name="ItemNumber" type="n0:numeric4"/>
     <xsd:element minOccurs="0" name="SubItem" type="n0:numeric3"/>
     <xsd:element minOccurs="0" name="CompanyCode" type="n0:char4"/>
     <xsd:element minOccurs="0" name="ClearingStatus" type="n0:char1"/>
     <xsd:element minOccurs="0" name="BusinessPartner" type="n0:char10"/>
     <xsd:element minOccurs="0" name="RefSpecificationContract" type="n0:char20"/>
     <xsd:element minOccurs="0" name="ContractAccount" type="n0:char12"/>
     <xsd:element minOccurs="0" name="MainTransaction" type="n0:char4"/>
     <xsd:element minOccurs="0" name="SubTransaction" type="n0:char4"/>
     <xsd:element minOccurs="0" name="Division" type="n0:char2"/>
     <xsd:element minOccurs="0" name="DocumentDate" type="n0:char10"/>
     <xsd:element minOccurs="0" name="PostingDate" type="n0:char10"/>
     <xsd:element minOccurs="0" name="NetPaymentDueDate" type="n0:char10"/>
     <xsd:element minOccurs="0" name="Amount" type="tns:IsuC4cUtilAmount"/>
     <xsd:element minOccurs="0" name="Status" type="n0:char1"/>
     <xsd:element minOccurs="0" name="PrintDocument" type="n0:char12"/>
     <xsd:element minOccurs="0" name="DocumentPostingDate" type="n0:char10"/>
     <xsd:element minOccurs="0" name="OpenAmount" type="tns:IsuC4cUtilAmount"/>
     <xsd:element minOccurs="0" name="ClearingDocument" type="n0:char12"/>
     <xsd:element minOccurs="0" name="PrintDate" type="n0:char10"/>
     <xsd:element minOccurs="0" name="PaymentDate" type="n0:char10"/>
     <xsd:element minOccurs="0" name="PplanPrintDocument" type="n0:char12"/>
     <xsd:element minOccurs="0" name="DifferenceAmount" type="tns:IsuC4cUtilAmount"/>
     <xsd:element minOccurs="0" name="ConsumptionAmount" type="tns:IsuC4cUtilAmount"/>
     <xsd:element minOccurs="0" name="StartDate" type="n0:char10"/>
     <xsd:element minOccurs="0" name="EndDate" type="n0:char10"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cUtilAmount">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="Amount" type="n0:curr13.2"/>
     <xsd:element minOccurs="0" name="Currency" type="n0:cuky5"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SPaymentPlanEdit">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="PaymentPlanId" type="n0:char12"/>
     <xsd:element minOccurs="0" name="Contract" type="n0:char10"/>
     <xsd:element minOccurs="0" name="LongText" type="n0:char132"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SPplanGetDetails">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="PplanHeader" type="tns:IsuC4cV2SPplanHeader"/>
     <xsd:element minOccurs="0" name="PplanItems" type="tns:IsuC4cV2TPplanItems"/>
     <xsd:element minOccurs="0" name="PplanContract" type="tns:IsuC4cV2SPplanContract"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SPplanContract">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="Contract" type="n0:char10"/>
     <xsd:element minOccurs="0" name="CompanyCode" type="n0:char4"/>
     <xsd:element minOccurs="0" name="Division" type="n0:char2"/>
     <xsd:element minOccurs="0" name="MoveInDate" type="n0:char10"/>
     <xsd:element minOccurs="0" name="AlternativePplanStartMonth" type="n0:numeric2"/>
     <xsd:element minOccurs="0" name="PaymentPlanType" type="n0:char4"/>
     <xsd:element minOccurs="0" name="PaymentPlanStartMonth" type="n0:numeric2"/>
     <xsd:element minOccurs="0" name="CurrDiffAmnt" type="tns:IsuC4cUtilAmount"/>
     <xsd:element minOccurs="0" name="MoveOutDate" type="n0:char10"/>
     <xsd:element minOccurs="0" name="DivisionCategory" type="tns:numeric2"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SPplanHeader">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="PaymentPlanId" type="n0:char12"/>
     <xsd:element minOccurs="0" name="Contract" type="n0:char10"/>
     <xsd:element minOccurs="0" name="BusinessPartner" type="n0:char10"/>
     <xsd:element minOccurs="0" name="ContractAccount" type="n0:char12"/>
     <xsd:element minOccurs="0" name="StartBillingPeriod" type="n0:char10"/>
     <xsd:element minOccurs="0" name="EndBillingPeriod" type="n0:char10"/>
     <xsd:element minOccurs="0" name="PaymentPlanType" type="n0:char4"/>
     <xsd:element minOccurs="0" name="StopDatePpPayment" type="n0:char10"/>
     <xsd:element minOccurs="0" name="DeactivationPaymentPlan" type="n0:char12"/>
     <xsd:element minOccurs="0" name="PaymentPlanCreationType" type="n0:numeric1"/>
     <xsd:element minOccurs="0" name="CreationDate" type="n0:char10"/>
     <xsd:element minOccurs="0" name="BbCycle" type="n0:numeric2"/>
     <xsd:element minOccurs="0" name="LongText" type="n0:char132"/>
     <xsd:element minOccurs="0" name="Text" type="n0:char30"/>
     <xsd:element minOccurs="0" name="AlternativeCaCollBills" type="n0:char12"/>
     <xsd:element minOccurs="0" name="Status" type="n0:char1"/>
     <xsd:element minOccurs="0" name="BillingDoc" type="n0:char12"/>
     <xsd:element minOccurs="0" name="PrintdocPaymentPlan" type="n0:char12"/>
     <xsd:element minOccurs="0" name="RemainingAmt" type="tns:IsuC4cUtilAmount"/>
     <xsd:element minOccurs="0" name="BillDocAdjustmnt" type="n0:char12"/>
     <xsd:element minOccurs="0" name="NoOfContracts" type="tns:char4"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SPaymentPlan">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="Contract" type="n0:char10"/>
     <xsd:element minOccurs="0" name="PaymentPlanType" type="n0:char4"/>
     <xsd:element minOccurs="0" name="StartMonthPplan" type="n0:numeric2"/>
     <xsd:element minOccurs="0" name="PaymentPlanYear" type="n0:numeric4"/>
     <xsd:element minOccurs="0" name="AlternativeStartMonth" type="n0:numeric2"/>
     <xsd:element minOccurs="0" name="LongText" type="n0:char132"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SPplanSimulate">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="Contract" type="n0:char10"/>
     <xsd:element minOccurs="0" name="PaymentPlanType" type="n0:char4"/>
     <xsd:element minOccurs="0" name="StartMonthPplan" type="n0:numeric2"/>
     <xsd:element minOccurs="0" name="PaymentPlanYear" type="n0:numeric4"/>
     <xsd:element minOccurs="0" name="AlternativeStartMonth" type="n0:numeric2"/>
     <xsd:element minOccurs="0" name="PlanDate" type="n0:char10"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SPplanDeactivate">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="PaymentPlanId" type="n0:char12"/>
     <xsd:element minOccurs="0" name="Contract" type="n0:char10"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="Bapiret2T">
    <xsd:sequence>
     <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="tns:Bapiret2"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2TPplanItems">
    <xsd:sequence>
     <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="tns:IsuC4cV2SPplanItems"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2TPplanGetDetails">
    <xsd:sequence>
     <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="tns:IsuC4cV2SPplanGetDetails"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:element name="IsuC4cV2PaymentPlanDelete">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IsAudit" type="tns:IsuC4cV2SAuditLog"/>
      <xsd:element minOccurs="0" name="IsPplanDelete" type="tns:IsuC4cV2SPplanDelete"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PaymentPlanDeleteResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EtMessage" type="tns:Bapiret2T"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PaymentPlanEdit">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IsAudit" type="tns:IsuC4cV2SAuditLog"/>
      <xsd:element minOccurs="0" name="IsPplanEdit" type="tns:IsuC4cV2SPaymentPlanEdit"/>
      <xsd:element minOccurs="0" name="ItPaymentPlanItems" type="tns:IsuC4cV2TPplanItems"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PaymentPlanEditResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EtMessage" type="tns:Bapiret2T"/>
      <xsd:element minOccurs="0" name="EtPaymentPlan" type="tns:IsuC4cV2TPplanGetDetails"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PaymentPlanCreate">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IsAudit" type="tns:IsuC4cV2SAuditLog"/>
      <xsd:element minOccurs="0" name="IsPplanCreate" type="tns:IsuC4cV2SPaymentPlan"/>
      <xsd:element minOccurs="0" name="ItPaymentPlanItems" type="tns:IsuC4cV2TPplanItems"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PaymentPlanCreateResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EtMessage" type="tns:Bapiret2T"/>
      <xsd:element minOccurs="0" name="EtPaymentPlan" type="tns:IsuC4cV2TPplanGetDetails"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PplanSimulation">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IsPplanSimulate" type="tns:IsuC4cV2SPplanSimulate"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PplanSimulationResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EsPaymentPlan" type="tns:IsuC4cV2SPplanGetDetails"/>
      <xsd:element minOccurs="0" name="EtMessage" type="tns:Bapiret2T"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PplanDeactivate">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IsAudit" type="tns:IsuC4cV2SAuditLog"/>
      <xsd:element minOccurs="0" name="IsPplanDeactivate" type="tns:IsuC4cV2SPplanDeactivate"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PplanDeactivateResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EtMessage" type="tns:Bapiret2T"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PaymentPlanGet">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IvBusinessPartner" type="n0:char10"/>
      <xsd:element minOccurs="0" name="IvContract" type="n0:char10"/>
      <xsd:element minOccurs="0" name="IvContractAccount" type="n0:char12"/>
      <xsd:element minOccurs="0" name="IvPaymentPlanId" type="n0:char12"/>
      <xsd:element minOccurs="0" name="IvPaymentPlanItemsRequired" type="n0:char1"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2PaymentPlanGetResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EtMessage" type="tns:Bapiret2T"/>
      <xsd:element minOccurs="0" name="EtPaymentPlan" type="tns:IsuC4cV2TPplanGetDetails"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
  </xsd:schema>
 </wsdl:types>
 <wsdl:message name="IsuC4cV2PaymentPlanDelete">
  <wsdl:part element="tns:IsuC4cV2PaymentPlanDelete" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PaymentPlanDeleteResponse">
  <wsdl:part element="tns:IsuC4cV2PaymentPlanDeleteResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PaymentPlanEdit">
  <wsdl:part element="tns:IsuC4cV2PaymentPlanEdit" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PaymentPlanEditResponse">
  <wsdl:part element="tns:IsuC4cV2PaymentPlanEditResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PaymentPlanCreate">
  <wsdl:part element="tns:IsuC4cV2PaymentPlanCreate" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PaymentPlanCreateResponse">
  <wsdl:part element="tns:IsuC4cV2PaymentPlanCreateResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PplanSimulation">
  <wsdl:part element="tns:IsuC4cV2PplanSimulation" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PplanSimulationResponse">
  <wsdl:part element="tns:IsuC4cV2PplanSimulationResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PplanDeactivate">
  <wsdl:part element="tns:IsuC4cV2PplanDeactivate" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PplanDeactivateResponse">
  <wsdl:part element="tns:IsuC4cV2PplanDeactivateResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PaymentPlanGet">
  <wsdl:part element="tns:IsuC4cV2PaymentPlanGet" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2PaymentPlanGetResponse">
  <wsdl:part element="tns:IsuC4cV2PaymentPlanGetResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:portType name="ISU_C4C_V2_PAYMENT_PLAN">
  <wsdl:documentation>
   <sapdoc:sapdoc xmlns:sapdoc="urn:sap:esi:documentation">
    <sapdoc:docitem docURL="http://ldciemt.wdf.sap.corp:50022/sap/bc/esdt/docu/sd_text?sap-client=350&amp;sd_name=ISU_C4C_V2_PAYMENT_PLAN"/>
    <sapdoc:docitem applicationComponent="IS-U-CS-C4C"/>
   </sapdoc:sapdoc>
  </wsdl:documentation>
  <wsp:Policy>
   <wsp:PolicyReference URI="#IF_IF_ISU_C4C_V2_PAYMENT_PLAN"/>
  </wsp:Policy>
  <wsdl:operation name="IsuC4cV2PaymentPlanDelete">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2PaymentPlanDelete"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2PaymentPlanDelete"/>
   <wsdl:output message="tns:IsuC4cV2PaymentPlanDeleteResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2PaymentPlanEdit">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2PaymentPlanEdit"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2PaymentPlanEdit"/>
   <wsdl:output message="tns:IsuC4cV2PaymentPlanEditResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2PaymentPlanCreate">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2PaymentPlanCreate"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2PaymentPlanCreate"/>
   <wsdl:output message="tns:IsuC4cV2PaymentPlanCreateResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2PplanSimulation">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2PplanSimulation"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2PplanSimulation"/>
   <wsdl:output message="tns:IsuC4cV2PplanSimulationResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2PplanDeactivate">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2PplanDeactivate"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2PplanDeactivate"/>
   <wsdl:output message="tns:IsuC4cV2PplanDeactivateResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2PaymentPlanGet">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2PaymentPlanGet"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2PaymentPlanGet"/>
   <wsdl:output message="tns:IsuC4cV2PaymentPlanGetResponse"/>
  </wsdl:operation>
 </wsdl:portType>
</wsdl:definitions>