<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:sap-com:document:sap:soap:functions:mc-style">
 <wsdl:documentation>
  <sidl:sidl xmlns:sidl="http://www.sap.com/2007/03/sidl"/>
 </wsdl:documentation>
 <wsp:UsingPolicy wsdl:required="true"/>
 <wsp:Policy wsu:Id="IF_IF_ISU_C4C_V2_BUDGET_BILL_PLAN">
  <sapsession:Session xmlns:sapsession="http://www.sap.com/webas/630/soap/features/session/">
   <sapsession:enableSession>false</sapsession:enableSession>
  </sapsession:Session>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2BudgetBillGet">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2BudgetBillEdit">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2BudgetBillSim">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2BudgetBillDelete">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsp:Policy wsu:Id="OP_IF_OP_IsuC4cV2BudgetBillCreate">
  <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
  <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
  <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
  <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
 </wsp:Policy>
 <wsdl:types>
  <xsd:schema xmlns:n0="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:tns="urn:sap-com:document:sap:rfc:functions" attributeFormDefault="qualified" targetNamespace="urn:sap-com:document:sap:rfc:functions">
   <xsd:import namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
   <xsd:simpleType name="char1">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="1"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char10">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="10"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char12">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="12"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char132">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="132"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char20">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="20"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char220">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="220"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char30">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="30"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char32">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="32"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char4">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="4"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char40">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="40"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char50">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="50"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="cuky5">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="5"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="curr13.2">
    <xsd:restriction base="xsd:decimal">
     <xsd:totalDigits value="13"/>
     <xsd:fractionDigits value="2"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric1">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="1"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric3">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="3"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric4">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="4"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric6">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="6"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:complexType name="ISU_C4C_V2_S_BUDGET_BILL_ITEM">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="DOCUMENT_NUMBER" type="n1:char12"/>
     <xsd:element minOccurs="0" name="REPETITION_ITEM" type="n1:numeric3"/>
     <xsd:element minOccurs="0" name="ITEM_NUMBER" type="n1:numeric4"/>
     <xsd:element minOccurs="0" name="SUBITEM_NUMBER" type="n1:numeric3"/>
     <xsd:element minOccurs="0" name="COMPANY_CODE" type="n1:char4"/>
     <xsd:element minOccurs="0" name="CLEARING_STATUS" type="n1:char1"/>
     <xsd:element minOccurs="0" name="MAIN_TRANSACTION" type="n1:char4"/>
     <xsd:element minOccurs="0" name="SUB_TRANSACTION" type="n1:char4"/>
     <xsd:element minOccurs="0" name="ACCOUNT_DETERMINATION_ID" type="n0:char2"/>
     <xsd:element minOccurs="0" name="DIVISION" type="n1:char2"/>
     <xsd:element minOccurs="0" name="DIVISION_CATEGORY" type="n0:numeric2"/>
     <xsd:element minOccurs="0" name="LEGDER_ACCOUNT" type="n1:char10"/>
     <xsd:element minOccurs="0" name="DOCUMENT_DATE" type="n0:char10"/>
     <xsd:element minOccurs="0" name="POSTING_DATE" type="n0:char10"/>
     <xsd:element minOccurs="0" name="DUE_DATE" type="n0:char10"/>
     <xsd:element minOccurs="0" name="BILLING_AMOUNT" type="n1:ISU_C4C_UTIL_AMOUNT"/>
     <xsd:element minOccurs="0" name="STATUS" type="n1:char1"/>
     <xsd:element minOccurs="0" name="CLEARING_DOCUMENT" type="n1:char12"/>
     <xsd:element minOccurs="0" name="PRINT_DATE" type="n0:char10"/>
     <xsd:element minOccurs="0" name="PAYMENT_DATE" type="n0:char10"/>
     <xsd:element minOccurs="0" name="PRINT_DOCUMENT" type="n1:char12"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="ISU_C4C_UTIL_AMOUNT">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="AMOUNT" type="n1:curr13.2"/>
     <xsd:element minOccurs="0" name="CURRENCY" type="n1:cuky5"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="ISU_C4C_V2_T_BUDGET_BILL_ITEM">
    <xsd:sequence>
     <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="n1:ISU_C4C_V2_S_BUDGET_BILL_ITEM"/>
    </xsd:sequence>
   </xsd:complexType>
  </xsd:schema>
  <xsd:schema xmlns:n0="urn:sap-com:document:sap:rfc:functions" attributeFormDefault="qualified" targetNamespace="urn:sap-com:document:sap:soap:functions:mc-style">
   <xsd:import namespace="urn:sap-com:document:sap:rfc:functions"/>
   <xsd:simpleType name="char10">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="10"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char12">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="12"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="char50">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="50"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="lang">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="1"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="numeric2">
    <xsd:restriction base="xsd:string">
     <xsd:maxLength value="2"/>
     <xsd:pattern value="\d*"/>
    </xsd:restriction>
   </xsd:simpleType>
   <xsd:complexType name="IsuC4cV2SAuditLog">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="UserName" type="n0:char40"/>
     <xsd:element minOccurs="0" name="SystemId" type="tns:char50"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="Bapiret2">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="Type" type="n0:char1"/>
     <xsd:element minOccurs="0" name="Id" type="n0:char20"/>
     <xsd:element minOccurs="0" name="Number" type="n0:numeric3"/>
     <xsd:element minOccurs="0" name="Message" type="n0:char220"/>
     <xsd:element minOccurs="0" name="LogNo" type="n0:char20"/>
     <xsd:element minOccurs="0" name="LogMsgNo" type="n0:numeric6"/>
     <xsd:element minOccurs="0" name="MessageV1" type="n0:char50"/>
     <xsd:element minOccurs="0" name="MessageV2" type="n0:char50"/>
     <xsd:element minOccurs="0" name="MessageV3" type="n0:char50"/>
     <xsd:element minOccurs="0" name="MessageV4" type="n0:char50"/>
     <xsd:element minOccurs="0" name="Parameter" type="n0:char32"/>
     <xsd:element minOccurs="0" name="Row" type="xsd:int"/>
     <xsd:element minOccurs="0" name="Field" type="n0:char30"/>
     <xsd:element minOccurs="0" name="System" type="n0:char10"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SBudgetBillDet">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="DocumentNumber" type="n0:char12"/>
     <xsd:element minOccurs="0" name="Contract" type="n0:char20"/>
     <xsd:element minOccurs="0" name="CompanyCode" type="n0:char4"/>
     <xsd:element minOccurs="0" name="Division" type="n0:char2"/>
     <xsd:element minOccurs="0" name="DivisionCategory" type="tns:numeric2"/>
     <xsd:element minOccurs="0" name="MoveInDate" type="tns:char10"/>
     <xsd:element minOccurs="0" name="MoveOutDate" type="tns:char10"/>
     <xsd:element minOccurs="0" name="StartPeriod" type="tns:char10"/>
     <xsd:element minOccurs="0" name="EndPeriod" type="tns:char10"/>
     <xsd:element minOccurs="0" name="DeactivationInvoice" type="tns:char12"/>
     <xsd:element minOccurs="0" name="StopDate" type="tns:char10"/>
     <xsd:element minOccurs="0" name="CreationDate" type="tns:char10"/>
     <xsd:element minOccurs="0" name="BudgetBillingCycle" type="n0:numeric2"/>
     <xsd:element minOccurs="0" name="Amount" type="tns:IsuC4cUtilAmount"/>
     <xsd:element minOccurs="0" name="Text" type="n0:char132"/>
     <xsd:element minOccurs="0" name="AlternativeContractAccount" type="n0:char12"/>
     <xsd:element minOccurs="0" name="BillingDocument" type="n0:char12"/>
     <xsd:element minOccurs="0" name="RemainingAmount" type="n0:numeric1"/>
     <xsd:element minOccurs="0" name="NoOfContracts" type="n0:numeric4"/>
     <xsd:element minOccurs="0" name="CurrentDifferenceAmount" type="tns:IsuC4cUtilAmount"/>
     <xsd:element minOccurs="0" name="Items" type="tns:IsuC4cV2TBudgetBillItem"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cUtilAmount">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="Amount" type="n0:curr13.2"/>
     <xsd:element minOccurs="0" name="Currency" type="n0:cuky5"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2SBudgetBillItem">
    <xsd:sequence>
     <xsd:element minOccurs="0" name="DocumentNumber" type="n0:char12"/>
     <xsd:element minOccurs="0" name="RepetitionItem" type="n0:numeric3"/>
     <xsd:element minOccurs="0" name="ItemNumber" type="n0:numeric4"/>
     <xsd:element minOccurs="0" name="SubitemNumber" type="n0:numeric3"/>
     <xsd:element minOccurs="0" name="CompanyCode" type="n0:char4"/>
     <xsd:element minOccurs="0" name="ClearingStatus" type="n0:char1"/>
     <xsd:element minOccurs="0" name="MainTransaction" type="n0:char4"/>
     <xsd:element minOccurs="0" name="SubTransaction" type="n0:char4"/>
     <xsd:element minOccurs="0" name="AccountDeterminationId" type="tns:char2"/>
     <xsd:element minOccurs="0" name="Division" type="n0:char2"/>
     <xsd:element minOccurs="0" name="DivisionCategory" type="tns:numeric2"/>
     <xsd:element minOccurs="0" name="LegderAccount" type="n0:char10"/>
     <xsd:element minOccurs="0" name="DocumentDate" type="tns:char10"/>
     <xsd:element minOccurs="0" name="PostingDate" type="tns:char10"/>
     <xsd:element minOccurs="0" name="DueDate" type="tns:char10"/>
     <xsd:element minOccurs="0" name="BillingAmount" type="tns:IsuC4cUtilAmount"/>
     <xsd:element minOccurs="0" name="Status" type="n0:char1"/>
     <xsd:element minOccurs="0" name="ClearingDocument" type="n0:char12"/>
     <xsd:element minOccurs="0" name="PrintDate" type="tns:char10"/>
     <xsd:element minOccurs="0" name="PaymentDate" type="tns:char10"/>
     <xsd:element minOccurs="0" name="PrintDocument" type="n0:char12"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="Bapiret2T">
    <xsd:sequence>
     <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="tns:Bapiret2"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2TBudgetBillDet">
    <xsd:sequence>
     <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="tns:IsuC4cV2SBudgetBillDet"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="IsuC4cV2TBudgetBillItem">
    <xsd:sequence>
     <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="tns:IsuC4cV2SBudgetBillItem"/>
    </xsd:sequence>
   </xsd:complexType>
   <xsd:element name="IsuC4cV2BudgetBillCreate">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IsAudit" type="tns:IsuC4cV2SAuditLog"/>
      <xsd:element minOccurs="0" name="ItBudgetBillingItem" type="n0:ISU_C4C_V2_T_BUDGET_BILL_ITEM"/>
      <xsd:element minOccurs="0" name="IvBudgetBillingDate" type="tns:char10"/>
      <xsd:element minOccurs="0" name="IvBudgetBillingText" type="n0:char132"/>
      <xsd:element minOccurs="0" name="IvContract" type="tns:char10"/>
      <xsd:element minOccurs="0" name="IvLanguage" type="tns:lang"/>
      <xsd:element minOccurs="0" name="IvProcedure" type="n0:char1"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2BudgetBillCreateResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EtCreate" type="tns:IsuC4cV2TBudgetBillDet"/>
      <xsd:element minOccurs="0" name="EtReturn" type="tns:Bapiret2T"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2BudgetBillDelete">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IsAudit" type="tns:IsuC4cV2SAuditLog"/>
      <xsd:element minOccurs="0" name="IvDocumentNumber" type="n0:char12"/>
      <xsd:element minOccurs="0" name="IvProcedure" type="n0:char1"/>
      <xsd:element minOccurs="0" name="IvUpdateEverTable" type="n0:char1"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2BudgetBillDeleteResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EtReturn" type="tns:Bapiret2T"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2BudgetBillSim">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IvBudgetBillingDate" type="tns:char10"/>
      <xsd:element minOccurs="0" name="IvContract" type="tns:char10"/>
      <xsd:element minOccurs="0" name="IvProcedure" type="n0:char1"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2BudgetBillSimResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EtReturn" type="tns:Bapiret2T"/>
      <xsd:element minOccurs="0" name="EtSimulate" type="tns:IsuC4cV2TBudgetBillDet"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2BudgetBillEdit">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IsAudit" type="tns:IsuC4cV2SAuditLog"/>
      <xsd:element minOccurs="0" name="ItBudgetBillingItem" type="n0:ISU_C4C_V2_T_BUDGET_BILL_ITEM"/>
      <xsd:element minOccurs="0" name="IvBudgetBillingText" type="n0:char132"/>
      <xsd:element minOccurs="0" name="IvContract" type="tns:char10"/>
      <xsd:element minOccurs="0" name="IvDocumentNumber" type="n0:char12"/>
      <xsd:element minOccurs="0" name="IvLanguage" type="tns:lang"/>
      <xsd:element minOccurs="0" name="IvProcedure" type="n0:char1"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2BudgetBillEditResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EtEdit" type="tns:IsuC4cV2TBudgetBillDet"/>
      <xsd:element minOccurs="0" name="EtReturn" type="tns:Bapiret2T"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2BudgetBillGet">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="IvBudgetBillingDate" type="tns:char10"/>
      <xsd:element minOccurs="0" name="IvBudgetBillingItemFlag" type="n0:char1"/>
      <xsd:element minOccurs="0" name="IvBusinessPartner" type="n0:char10"/>
      <xsd:element minOccurs="0" name="IvContract" type="tns:char10"/>
      <xsd:element minOccurs="0" name="IvContractAccount" type="n0:char12"/>
      <xsd:element minOccurs="0" name="IvDocumentNumber" type="n0:char12"/>
      <xsd:element minOccurs="0" name="IvFetchContracts" type="n0:char1"/>
      <xsd:element minOccurs="0" name="IvProcedure" type="n0:char1"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="IsuC4cV2BudgetBillGetResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element minOccurs="0" name="EtGet" type="tns:IsuC4cV2TBudgetBillDet"/>
      <xsd:element minOccurs="0" name="EtReturn" type="tns:Bapiret2T"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
  </xsd:schema>
 </wsdl:types>
 <wsdl:message name="IsuC4cV2BudgetBillCreate">
  <wsdl:part element="tns:IsuC4cV2BudgetBillCreate" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2BudgetBillCreateResponse">
  <wsdl:part element="tns:IsuC4cV2BudgetBillCreateResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2BudgetBillDelete">
  <wsdl:part element="tns:IsuC4cV2BudgetBillDelete" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2BudgetBillDeleteResponse">
  <wsdl:part element="tns:IsuC4cV2BudgetBillDeleteResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2BudgetBillSim">
  <wsdl:part element="tns:IsuC4cV2BudgetBillSim" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2BudgetBillSimResponse">
  <wsdl:part element="tns:IsuC4cV2BudgetBillSimResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2BudgetBillEdit">
  <wsdl:part element="tns:IsuC4cV2BudgetBillEdit" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2BudgetBillEditResponse">
  <wsdl:part element="tns:IsuC4cV2BudgetBillEditResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2BudgetBillGet">
  <wsdl:part element="tns:IsuC4cV2BudgetBillGet" name="parameters"/>
 </wsdl:message>
 <wsdl:message name="IsuC4cV2BudgetBillGetResponse">
  <wsdl:part element="tns:IsuC4cV2BudgetBillGetResponse" name="parameter"/>
 </wsdl:message>
 <wsdl:portType name="ISU_C4C_V2_BUDGET_BILL_PLAN">
  <wsdl:documentation>
   <sapdoc:sapdoc xmlns:sapdoc="urn:sap:esi:documentation">
    <sapdoc:docitem docURL="http://ldciemt.wdf.sap.corp:50022/sap/bc/esdt/docu/sd_text?sap-client=350&amp;sd_name=ISU_C4C_V2_BUDGET_BILL_PLAN"/>
    <sapdoc:docitem applicationComponent="IS-U-CS-C4C"/>
   </sapdoc:sapdoc>
  </wsdl:documentation>
  <wsp:Policy>
   <wsp:PolicyReference URI="#IF_IF_ISU_C4C_V2_BUDGET_BILL_PLAN"/>
  </wsp:Policy>
  <wsdl:operation name="IsuC4cV2BudgetBillCreate">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2BudgetBillCreate"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2BudgetBillCreate"/>
   <wsdl:output message="tns:IsuC4cV2BudgetBillCreateResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2BudgetBillDelete">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2BudgetBillDelete"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2BudgetBillDelete"/>
   <wsdl:output message="tns:IsuC4cV2BudgetBillDeleteResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2BudgetBillSim">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2BudgetBillSim"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2BudgetBillSim"/>
   <wsdl:output message="tns:IsuC4cV2BudgetBillSimResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2BudgetBillEdit">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2BudgetBillEdit"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2BudgetBillEdit"/>
   <wsdl:output message="tns:IsuC4cV2BudgetBillEditResponse"/>
  </wsdl:operation>
  <wsdl:operation name="IsuC4cV2BudgetBillGet">
   <wsp:Policy>
    <wsp:PolicyReference URI="#OP_IF_OP_IsuC4cV2BudgetBillGet"/>
   </wsp:Policy>
   <wsdl:input message="tns:IsuC4cV2BudgetBillGet"/>
   <wsdl:output message="tns:IsuC4cV2BudgetBillGetResponse"/>
  </wsdl:operation>
 </wsdl:portType>
</wsdl:definitions>